"use client";

import { useEffect, useMemo, useState } from "react";

type Tab = "home" | "journey" | "study" | "practice" | "flashcards" | "quiz" | "test" | "airports" | "notes" | "calendar" | "passport" | "ai" | "phonetic";
type Note = { id: number; text: string; color: string; size: string; bold: boolean };
type CalendarEvent = { id: number; date: string; title: string; type: string };
type Course = { title: string; subtitle: string; icon: string; lessons: string[] };
type Airport = { city: string; code: string; region: string };

const airports: Airport[] = [
  ["Akron / Canton", "CAK", "US"], ["Albany", "ALB", "US"], ["Arcata / Eureka", "ACV", "US"], ["Atlantic City", "ACY", "US"],
  ["Baltimore", "BWI", "US"], ["Bangor", "BGR", "US"], ["Birmingham", "BHM", "US"], ["Brownsville", "BRO", "US"],
  ["Burbank", "BUR", "US"], ["Burlington", "BTV", "US"], ["Cancún", "CUN", "International"], ["Charleston, SC", "CHS", "US"],
  ["Charleston, WV", "CRW", "US"], ["Cincinnati", "CVG", "US"], ["Columbus", "CMH", "US"], ["Dallas / Fort Worth", "DFW", "US"],
  ["Dayton", "DAY", "US"], ["Daytona Beach", "DAB", "US"], ["Denver", "DEN", "US"], ["Erie", "ERI", "US"],
  ["Evansville", "EVV", "US"], ["Fayetteville / Northwest Arkansas", "XNA", "US"], ["Fort Lauderdale", "FLL", "US"], ["Fort Myers", "RSW", "US"],
  ["Grand Junction", "GJT", "US"], ["Greensboro", "GSO", "US"], ["Greenville / Spartanburg", "GSP", "US"], ["Gulfport / Biloxi", "GPT", "US"],
  ["Hartford", "BDL", "US"], ["Huntsville", "HSV", "US"], ["Jacksonville", "JAX", "US"], ["Key West", "EYW", "US"],
  ["Lancaster", "LNS", "US"], ["Lansing", "LAN", "US"], ["Las Vegas", "LAS", "US"], ["Lincoln", "LNK", "US"],
  ["Long Island / Islip", "ISP", "US"], ["Los Angeles", "LAX", "US"], ["Louisville", "SDF", "US"], ["Madison", "MSN", "US"],
  ["Manchester", "MHT", "US"], ["Memphis", "MEM", "US"], ["Montrose", "MTJ", "US"], ["Myrtle Beach", "MYR", "US"],
  ["Nassau", "NAS", "International"], ["New Bern", "EWN", "US"], ["New Haven", "HVN", "US"], ["New Orleans", "MSY", "US"],
  ["Newark", "EWR", "US"], ["Newburgh / Stewart", "SWF", "US"], ["Norfolk", "ORF", "US"], ["Ogden", "OGD", "US"],
  ["Ogdensburg", "OGS", "US"], ["Orange County", "SNA", "US"], ["Orlando", "MCO", "US"], ["Pensacola", "PNS", "US"],
  ["Phoenix", "PHX", "US"], ["Pittsburgh", "PIT", "US"], ["Portland, ME", "PWM", "US"], ["Portsmouth", "PSM", "US"],
  ["Providence", "PVD", "US"], ["Provo", "PVU", "US"], ["Punta Cana", "PUJ", "International"], ["Raleigh / Durham", "RDU", "US"],
  ["Redmond / Bend", "RDM", "US"], ["Richmond", "RIC", "US"], ["Rochester", "ROC", "US"], ["Salisbury / Ocean City", "SBY", "US"],
  ["San Antonio", "SAT", "US"], ["San Bernardino", "SBD", "US"], ["San Diego", "SAN", "US"], ["San Francisco", "SFO", "US"],
  ["San José, Costa Rica", "SJO", "International"], ["Sarasota / Bradenton", "SRQ", "US"], ["Savannah", "SAV", "US"], ["Scranton", "AVP", "US"],
  ["South Bend", "SBN", "US"], ["Springfield, IL", "SPI", "US"], ["St. Thomas", "STT", "International"], ["Syracuse", "SYR", "US"],
  ["Tallahassee", "TLH", "US"], ["Tampa Bay", "TPA", "US"], ["Trenton", "TTN", "US"], ["Tri-Cities", "TRI", "US"],
  ["Twin Falls", "TWF", "US"], ["Vero Beach", "VRB", "US"], ["Washington / Dulles", "IAD", "US"], ["West Palm Beach", "PBI", "US"],
  ["White Plains", "HPN", "US"], ["Wilmington, NC", "ILM", "US"],
].map(([city, code, region]) => ({ city, code, region }));

const courses: Course[] = [
  { title: "Aviation Foundations", subtitle: "Aircraft, airline basics & terminology", icon: "✈", lessons: ["Cabin crew role and aviation terminology", "UTC / Zulu time basics", "IATA airport codes", "ICAO phonetic alphabet"] },
  { title: "Emergency Procedures", subtitle: "Safety, evacuation & abnormal situations", icon: "✦", lessons: ["Emergency priorities", "Evacuation fundamentals", "Crew communication", "Equipment familiarization — training-guide dependent"] },
  { title: "Safety & Security", subtitle: "Cabin security, compliance & awareness", icon: "◇", lessons: ["Security awareness", "Cabin checks", "Standardized communication", "Source-first review from your uploaded package"] },
  { title: "Service & Hospitality", subtitle: "Guest experience from boarding to landing", icon: "○", lessons: ["Guest experience", "Boarding and cabin flow", "Service standards", "Breeze-specific material from your uploaded package"] },
  { title: "Onboard Operations", subtitle: "Cabin flow, equipment & procedures", icon: "▱", lessons: ["Preflight workflow", "Cabin operations", "Equipment and procedures", "Source-first review from your uploaded package"] },
  { title: "Medical & First Aid", subtitle: "Recognizing and responding to medical events", icon: "＋", lessons: ["Medical response fundamentals", "First-aid principles", "Communication and escalation", "Airline-specific procedures from your uploaded package"] },
  { title: "Breeze Knowledge", subtitle: "Airline-specific policies & standards", icon: "✦", lessons: ["Breeze terminology", "Company knowledge", "Policies and standards", "Only verified content from your uploaded training material"] },
  { title: "Final Cabin Check", subtitle: "Mixed review before training day", icon: "✓", lessons: ["Mixed review", "Weak-area practice", "Flashcard review", "Final knowledge check"] },
];
const phonetic = [["A","Alpha"],["B","Bravo"],["C","Charlie"],["D","Delta"],["E","Echo"],["F","Foxtrot"],["G","Golf"],["H","Hotel"],["I","India"],["J","Juliett"],["K","Kilo"],["L","Lima"],["M","Mike"],["N","November"],["O","Oscar"],["P","Papa"],["Q","Quebec"],["R","Romeo"],["S","Sierra"],["T","Tango"],["U","Uniform"],["V","Victor"],["W","Whiskey"],["X","X-ray"],["Y","Yankee"],["Z","Zulu"]];
const practiceQuestions = [
  { q: "Zulu (Z) is another name for which time reference?", options: ["UTC", "Local daylight time only", "Eastern Time", "The destination's local time"], answer: 0, why: "Zulu time (Z) is the aviation designation for UTC±00:00." },
  { q: "A location is UTC−5. Local time is 14:00. What is Zulu?", options: ["09:00Z", "14:00Z", "19:00Z", "05:00Z"], answer: 2, why: "UTC−5 means local time is five hours behind UTC. Add 5 hours: 14:00 + 5 = 19:00Z." },
  { q: "A location is UTC+3. Local time is 18:00. What is Zulu?", options: ["21:00Z", "15:00Z", "18:00Z", "03:00Z"], answer: 1, why: "UTC+3 means local time is three hours ahead of UTC. Subtract 3 hours: 18:00 − 3 = 15:00Z." },
  { q: "If Zulu is 02:00Z and the location is UTC−4, what is local time?", options: ["22:00 local (previous day)", "06:00 local", "02:00 local", "04:00 local"], answer: 0, why: "UTC−4 means local time is four hours behind UTC. 02:00Z − 4 hours = 22:00 on the previous calendar day." },
];
const quizQuestions = [
  { q: "What does IAD identify?", options: ["Washington Dulles International Airport", "Baltimore/Washington International", "Newark Liberty International", "Long Island MacArthur Airport"], answer: 0, why: "IAD is the IATA code for Washington Dulles International Airport." },
  { q: "Which word represents the letter A in the ICAO phonetic alphabet?", options: ["Alpha", "Aviation", "Able", "Atlas"], answer: 0, why: "A is Alpha." },
  { q: "Which statement about Zulu time is correct?", options: ["Zulu is UTC", "Zulu is always local time", "Zulu is Eastern Time", "Zulu changes with daylight saving time"], answer: 0, why: "Zulu (Z) is the aviation term for UTC." },
  { q: "What is the best source for Breeze-specific training procedures?", options: ["Your official training material", "A random social-media post", "A generic quiz website", "A rumor from another trainee"], answer: 0, why: "Airline-specific procedures should be learned from the official training material provided for your training." },
];
const flashcards = [["UTC", "Coordinated Universal Time; the zero-offset reference used for Zulu time."],["Zulu / Z", "Aviation designation for UTC. Example: 1530Z = 15:30 UTC."],["IATA code", "A three-letter airport identifier such as IAD, MCO or SFO."],["ICAO phonetic alphabet", "The standardized spelling alphabet: Alpha, Bravo, Charlie … Zulu."],["Crew communication", "Use concise, standardized language and confirm important instructions."]];
const colors = ["#fffdf8", "#f2e8dc", "#e4eee2", "#e7e4ef", "#f3e2e2"];
function formatDate(d: Date) { return d.toISOString().slice(0, 10); }
function localDate(y: number, m: number, day: number) { return new Date(y, m, day); }

export default function Home() {
  const [tab, setTab] = useState<Tab>("home"); const [completed, setCompleted] = useState(0); const [query, setQuery] = useState("");
  const [notes, setNotes] = useState<Note[]>([]); const [noteDraft, setNoteDraft] = useState(""); const [editingId, setEditingId] = useState<number | null>(null);
  const [calendarDate, setCalendarDate] = useState(new Date(2026, 8, 1)); const [events, setEvents] = useState<CalendarEvent[]>([]); const [eventTitle, setEventTitle] = useState(""); const [eventType, setEventType] = useState("Study"); const [selectedDate, setSelectedDate] = useState(formatDate(new Date()));
  const [selectedCourse, setSelectedCourse] = useState(0); const [practiceIndex, setPracticeIndex] = useState(0); const [practiceAnswer, setPracticeAnswer] = useState<number | null>(null);
  const [quizIndex, setQuizIndex] = useState(0); const [quizAnswer, setQuizAnswer] = useState<number | null>(null); const [quizScore, setQuizScore] = useState(0); const [testIndex, setTestIndex] = useState(0); const [testAnswer, setTestAnswer] = useState<number | null>(null); const [testScore, setTestScore] = useState(0);
  const [cardIndex, setCardIndex] = useState(0); const [cardFlip, setCardFlip] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [aiInput, setAiInput] = useState(""); const [aiResponse, setAiResponse] = useState(""); const [aiBusy, setAiBusy] = useState(false); const [pdfName, setPdfName] = useState(""); const [aiError, setAiError] = useState(""); const [signedIn, setSignedIn] = useState(false);

  useEffect(() => { try { const saved = localStorage.getItem("cabinready-v1"); if (!saved) return; const data = JSON.parse(saved); setCompleted(data.completed ?? 0); setNotes(data.notes ?? []); setEvents(data.events ?? []); setSignedIn(data.signedIn ?? false); } catch {} }, []);
  useEffect(() => { localStorage.setItem("cabinready-v1", JSON.stringify({ completed, notes, events, signedIn })); }, [completed, notes, events, signedIn]);
  const filteredAirports = useMemo(() => airports.filter(a => `${a.city} ${a.code} ${a.region}`.toLowerCase().includes(query.toLowerCase())), [query]); const activeCourse = Math.min(completed, courses.length - 1); const todayEvents = events.filter(e => e.date === selectedDate);
  const nav = (next: Tab) => { setTab(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const addOrSaveNote = () => { if (!noteDraft.trim()) return; if (editingId !== null) setNotes(prev => prev.map(n => n.id === editingId ? { ...n, text: noteDraft.trim() } : n)); else setNotes(prev => [{ id: Date.now(), text: noteDraft.trim(), color: colors[0], size: "base", bold: false }, ...prev]); setNoteDraft(""); setEditingId(null); };
  const updateNote = (id: number, patch: Partial<Note>) => setNotes(prev => prev.map(n => n.id === id ? { ...n, ...patch } : n)); const deleteNote = (id: number) => setNotes(prev => prev.filter(n => n.id !== id));
  const monthDays = () => { const y = calendarDate.getFullYear(), m = calendarDate.getMonth(); const first = localDate(y, m, 1).getDay(); const count = new Date(y, m + 1, 0).getDate(); return [...Array(first).fill(null), ...Array.from({ length: count }, (_, i) => localDate(y, m, i + 1))]; };
  const addEvent = () => { if (!eventTitle.trim()) return; setEvents(prev => [...prev, { id: Date.now(), date: selectedDate, title: eventTitle.trim(), type: eventType }]); setEventTitle(""); };
  const answerPractice = (i: number) => { if (practiceAnswer === null) setPracticeAnswer(i); }; const nextPractice = () => { setPracticeIndex(i => (i + 1) % practiceQuestions.length); setPracticeAnswer(null); };
  const answerQuiz = (i: number) => { if (quizAnswer !== null) return; setQuizAnswer(i); if (i === quizQuestions[quizIndex].answer) setQuizScore(s => s + 1); }; const nextQuiz = () => { if (quizIndex === quizQuestions.length - 1) { setQuizIndex(0); setQuizScore(0); setQuizAnswer(null); } else { setQuizIndex(i => i + 1); setQuizAnswer(null); } };
  const answerTest = (i: number) => { if (testAnswer !== null) return; setTestAnswer(i); if (i === quizQuestions[testIndex].answer) setTestScore(s => s + 1); }; const nextTest = () => { if (testIndex === quizQuestions.length - 1) { setTestIndex(0); setTestScore(0); setTestAnswer(null); } else { setTestIndex(i => i + 1); setTestAnswer(null); } };
  const uploadPdf = async (file: File) => { if (!file.name.toLowerCase().endsWith(".pdf")) { setAiError("Please upload a PDF."); return; } setPdfName(file.name); setAiError(""); setAiResponse("PDF queued. When your AI API key is connected, CabinReady will scan the PDF, identify the training topics, and route material into the matching course."); };
  const askAI = async () => { if (!aiInput.trim()) return; setAiBusy(true); setAiError(""); try { const res = await fetch("/api/ai", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt: aiInput }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "AI is not connected yet."); setAiResponse(data.text || "No response returned."); } catch (e) { setAiError(e instanceof Error ? e.message : "AI is not connected yet."); } finally { setAiBusy(false); } };
  const completeCourse = () => { if (selectedCourse === completed) setCompleted(c => Math.min(c + 1, courses.length)); };

  return <main className="app-shell"><div className="app-frame"><header className="topbar"><button onClick={() => nav("home")} className="brand"><span className="brand-mark">✈</span><span><strong>CabinReady</strong><small>flight attendant training</small></span></button><div className="top-actions"><span className="date-pill">OCT 2026</span><button className="account-pill" onClick={() => setSignedIn(v => !v)}>{signedIn ? "✓ Saved" : "Sign in"}</button></div></header>
    {tab === "home" && <><section className="hero-grid"><div className="hero-copy"><span className="eyebrow">TRAINING DAY PREP</span><h1>Let&apos;s get<br />cabin-ready.</h1><p className="hero-quote">“You don&apos;t have to know everything today. You just have to keep learning.”</p><button className="dark-btn" onClick={() => nav("practice")}>Start practice <span>→</span></button></div><div className="hero-card"><div className="mini-label">Your next move</div><div className="hero-course"><span className="plane-badge">✈</span><div><strong>{courses[activeCourse].title}</strong><span>{completed}/8 courses completed</span></div></div><div className="mini-route">{courses.map((_, i) => <i key={i} className={i < completed ? "done" : i === activeCourse ? "current" : ""} />)}</div><button className="text-btn" onClick={() => nav("journey")}>Open training journey →</button></div></section><section className="home-grid"><HomeCard title="Study" eyebrow="LEARN" text="Courses, study guides, flashcards and your uploaded training package." onClick={() => nav("study")} /><HomeCard title="Practice" eyebrow="BUILD SKILL" text="Airport codes, Zulu/UTC calculations, phonetic alphabet and practice questions." onClick={() => nav("practice")} /><HomeCard title="Calendar" eyebrow="STAY ON TRACK" text="Keep exams, homework, study sessions and training milestones in one place." onClick={() => nav("calendar")} /><HomeCard title="My notes" eyebrow="REMEMBER" text="Write, edit, highlight and format the things you want to keep." onClick={() => nav("notes")} /></section><section className="quick-strip"><div><span className="eyebrow">TODAY</span><strong>Keep your study space simple.</strong></div><button onClick={() => nav("passport")}>View passport →</button></section></>}
    {tab === "journey" && <Journey courses={courses} completed={completed} selectedCourse={selectedCourse} setSelectedCourse={(i) => { setSelectedCourse(i); nav("study"); }} onHome={() => nav("home")} />}
    {tab === "study" && <Study courses={courses} completed={completed} selectedCourse={selectedCourse} setSelectedCourse={setSelectedCourse} onComplete={completeCourse} onHome={() => nav("home")} onAI={() => nav("ai")} />}
    {tab === "passport" && <Passport courses={courses} completed={completed} events={events} onHome={() => nav("home")} onJourney={() => nav("journey")} />}
    {tab === "airports" && <section className="page-section"><Back onClick={() => nav("home")} /><div className="page-head"><div><span className="eyebrow">BREEZE NETWORK</span><h2>Airport codes</h2><p>Search by city or IATA code. Breeze&apos;s official destination list currently includes 90+ cities across the U.S. and international markets.</p></div><span className="count-pill">{airports.length} entries</span></div><input className="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search airport or code…" /><div className="airport-grid">{filteredAirports.map(a => <div className="airport-card" key={a.code}><span>{a.region === "International" ? "INTL" : "US"}</span><strong>{a.code}</strong><div>{a.city}</div></div>)}</div><div className="notice">Puerto Rico and Jamaica are not included as current Breeze destinations here because Breeze&apos;s current public destination list does not list them.</div></section>}
    {tab === "notes" && <section className="page-section"><Back onClick={() => nav("home")} /><div className="page-head"><div><span className="eyebrow">REMEMBER</span><h2>My notes</h2><p>Capture key points from your study package instead of rewriting everything.</p></div></div><div className="note-editor"><textarea value={noteDraft} onChange={e => setNoteDraft(e.target.value)} placeholder="Write a note…" /><div className="editor-actions"><button className="dark-btn small" onClick={addOrSaveNote}>{editingId ? "Save changes" : "Add note"}</button>{editingId && <button className="light-btn" onClick={() => { setEditingId(null); setNoteDraft(""); }}>Cancel</button>}</div></div><div className="notes-list">{notes.length === 0 ? <Empty text="Your saved notes will appear here." /> : notes.map(note => <article className="note-card" key={note.id} style={{ background: note.color }}><div className={`note-text note-${note.size} ${note.bold ? "note-bold" : ""}`}>{note.text}</div><div className="note-controls"><button onClick={() => updateNote(note.id, { bold: !note.bold })}>B</button><button onClick={() => updateNote(note.id, { size: note.size === "sm" ? "base" : note.size === "base" ? "lg" : "sm" })}>A↕</button>{colors.map(c => <button key={c} style={{ background: c }} aria-label="change note color" onClick={() => updateNote(note.id, { color: c })} />)}<button onClick={() => { setEditingId(note.id); setNoteDraft(note.text); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Edit</button><button onClick={() => deleteNote(note.id)}>Delete</button></div></article>)}</div></section>}
    {tab === "calendar" && <section className="page-section"><Back onClick={() => nav("home")} /><div className="page-head"><div><span className="eyebrow">STAY ON TRACK</span><h2>Study calendar</h2><p>Track exams, homework, study blocks and training milestones.</p></div></div><div className="calendar-wrap"><div className="calendar-head"><button onClick={() => setCalendarDate(new Date(calendarDate.getFullYear(), calendarDate.getMonth() - 1, 1))}>←</button><strong>{calendarDate.toLocaleString("en-US", { month: "long", year: "numeric" })}</strong><button onClick={() => setCalendarDate(new Date(calendarDate.getFullYear(), calendarDate.getMonth() + 1, 1))}>→</button></div><div className="weekday">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{monthDays().map((d, i) => d ? <button key={i} onClick={() => setSelectedDate(formatDate(d))} className={selectedDate === formatDate(d) ? "selected-day" : ""}><span>{d.getDate()}</span>{events.filter(e => e.date === formatDate(d)).slice(0,2).map(e => <small key={e.id}>{e.type}</small>)}</button> : <div key={i} />)}</div></div><div className="event-panel"><div><span className="eyebrow">{selectedDate}</span><h3>Plan your day</h3></div><div className="event-form"><input value={eventTitle} onChange={e => setEventTitle(e.target.value)} placeholder="Exam, homework, study…" /><select value={eventType} onChange={e => setEventType(e.target.value)}><option>Study</option><option>Exam</option><option>Homework</option><option>Training</option><option>Reminder</option></select><button className="dark-btn small" onClick={addEvent}>Add</button></div>{todayEvents.length > 0 && <div className="event-list">{todayEvents.map(e => <div key={e.id}><span>{e.type}</span><strong>{e.title}</strong><button onClick={() => setEvents(prev => prev.filter(x => x.id !== e.id))}>×</button></div>)}</div>}</div></section>}
    {tab === "practice" && <section className="page-section"><Back onClick={() => nav("home")} /><div className="page-head"><div><span className="eyebrow">BUILD SKILL</span><h2>Practice lab</h2><p>Short drills with instant explanations. Start with UTC/Zulu, then move into the broader knowledge bank.</p></div></div><div className="tool-grid"><ToolCard title="UTC / Zulu" text="Practice converting between local time and Zulu using UTC offsets." onClick={() => nav("practice")} active /><ToolCard title="Airport codes" text="Search and memorize the Breeze network." onClick={() => nav("airports")} /><ToolCard title="Phonetic alphabet" text="A = Alpha through Z = Zulu." onClick={() => nav("phonetic")} /><ToolCard title="Question bank" text="Practice questions with explanations." onClick={() => nav("quiz")} /></div><PracticeQuestion index={practiceIndex} answer={practiceAnswer} onAnswer={answerPractice} onNext={nextPractice} /></section>}
    {tab === "phonetic" && <section className="page-section"><Back onClick={() => nav("practice")} /><div className="page-head"><div><span className="eyebrow">COMMUNICATION</span><h2>ICAO phonetic alphabet</h2><p>Learn the standardized spelling alphabet used to make letters clear over radio and telephone communication.</p></div></div><div className="phonetic-grid">{phonetic.map(([letter, word]) => <div key={letter}><strong>{letter}</strong><span>{word}</span></div>)}</div></section>}
    {tab === "flashcards" && <Flashcards cardIndex={cardIndex} flip={cardFlip} setFlip={setCardFlip} setIndex={setCardIndex} onHome={() => nav("home")} />}
    {tab === "quiz" && <Quiz title="Practice quiz" questions={quizQuestions} index={quizIndex} answer={quizAnswer} score={quizScore} onAnswer={answerQuiz} onNext={nextQuiz} onHome={() => nav("home")} />}
    {tab === "test" && <Quiz title="Final cabin check" questions={quizQuestions} index={testIndex} answer={testAnswer} score={testScore} onAnswer={answerTest} onNext={nextTest} onHome={() => nav("home")} final />}
    {tab === "ai" && <section className="page-section"><Back onClick={() => nav("home")} /><div className="page-head"><div><span className="eyebrow">AI STUDY ASSISTANT</span><h2>CabinReady AI</h2><p>Use AI to explain, quiz and organize your training material. Airline-specific answers should be grounded in your official training package.</p></div><span className="ai-badge">GPT-ready</span></div><div className="ai-panel"><label className="upload-box"><input type="file" accept="application/pdf" onChange={e => e.target.files?.[0] && uploadPdf(e.target.files[0])} /><span className="upload-icon">↑</span><strong>{pdfName || "Upload your training PDF"}</strong><small>{pdfName ? "PDF queued for AI processing" : "Your study package can be scanned and routed into the right course."}</small></label><div className="ai-chat"><textarea value={aiInput} onChange={e => setAiInput(e.target.value)} placeholder="Ask: Explain this topic simply…" /><button className="dark-btn" onClick={askAI} disabled={aiBusy}>{aiBusy ? "Thinking…" : "Ask AI →"}</button></div>{aiError && <div className="error-box">{aiError}</div>}{aiResponse && <div className="ai-response"><span className="eyebrow">CABINREADY AI</span><p>{aiResponse}</p></div>}</div><div className="notice">AI connection is intentionally separated from the client. Put your API key in Vercel environment variables; never paste the secret key into this page.</div></section>}
    <nav className="floating-nav"><button onClick={() => nav("home")}>⌂<span>Home</span></button><button onClick={() => nav("journey")}>✈<span>Journey</span></button><button onClick={() => nav("study")}>▤<span>Study</span></button><button onClick={() => nav("airports")}>⌖<span>Airports</span></button><button onClick={() => nav("notes")}>✎<span>Notes</span></button><button className="more-btn" onClick={() => setMenuOpen(v => !v)}>✦</button></nav>
    {menuOpen && <div className="menu-pop"><button onClick={() => nav("calendar")}>Calendar</button><button onClick={() => nav("passport")}>Training passport</button><button onClick={() => nav("practice")}>Practice lab</button><button onClick={() => nav("flashcards")}>Flashcards</button><button onClick={() => nav("quiz")}>Quiz</button><button onClick={() => nav("test")}>Final test</button><button onClick={() => nav("ai")}>AI assistant</button><button onClick={() => nav("phonetic")}>Phonetic alphabet</button></div>}
  </div></main>;
}
function HomeCard({ eyebrow, title, text, onClick }: { eyebrow: string; title: string; text: string; onClick: () => void }) { return <button className="home-card" onClick={onClick}><span className="eyebrow">{eyebrow}</span><strong>{title}</strong><p>{text}</p><span className="arrow">Open section →</span></button>; }
function ToolCard({ title, text, onClick, active }: { title: string; text: string; onClick: () => void; active?: boolean }) { return <button className={`tool-card ${active ? "active" : ""}`} onClick={onClick}><strong>{title}</strong><p>{text}</p><span>Open →</span></button>; }
function Back({ onClick }: { onClick: () => void }) { return <button className="back-btn" onClick={onClick}>← Back</button>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function Journey({ courses, completed, selectedCourse, setSelectedCourse, onHome }: { courses: Course[]; completed: number; selectedCourse: number; setSelectedCourse: (i:number)=>void; onHome:()=>void }) { return <section className="page-section"><Back onClick={onHome} /><div className="page-head"><div><span className="eyebrow">TRAINING ROUTE</span><h2>Your journey</h2><p>Your aircraft moves forward only when you complete the current course from inside its study page.</p></div><span className="count-pill">{completed}/8 complete</span></div><div className="journey-map"><div className="route-line" />{courses.map((c,i) => { const locked = i > completed; const done = i < completed; return <button key={c.title} disabled={locked} onClick={() => { if (!locked) setSelectedCourse(i); }} className={`journey-stop ${locked ? "locked" : ""} ${selectedCourse === i ? "selected" : ""}`}><span className="stop-icon">{done ? "✓" : locked ? "•" : c.icon}</span><strong>Course {i + 1}</strong><b>{c.title}</b><small>{locked ? "Locked — finish the previous checkpoint" : done ? "Completed" : "Current checkpoint"}</small></button>; })}</div><div className="aircraft-note"><span>✈</span><div><strong>Your aircraft is at Course {Math.min(completed + 1, 8)}</strong><p>{courses[Math.min(completed,7)].title} is the next checkpoint.</p></div></div></section>; }
function Study({ courses, completed, selectedCourse, setSelectedCourse, onComplete, onHome, onAI }: { courses: Course[]; completed:number; selectedCourse:number; setSelectedCourse:(i:number)=>void; onComplete:()=>void; onHome:()=>void; onAI:()=>void }) { const c = courses[selectedCourse]; const locked = selectedCourse > completed; return <section className="page-section"><Back onClick={onHome} /><div className="study-tabs">{courses.map((x,i)=><button key={x.title} disabled={i>completed} className={selectedCourse===i?"selected":""} onClick={()=>setSelectedCourse(i)}>C{i+1}</button>)}</div><div className="page-head"><div><span className="eyebrow">COURSE {selectedCourse+1} OF 8</span><h2>{c.title}</h2><p>{c.subtitle}</p></div>{locked ? <span className="count-pill">Locked</span> : <span className="count-pill">{selectedCourse < completed ? "Completed" : "Current"}</span>}</div>{locked ? <div className="locked-panel">Finish Course {selectedCourse} first. The route is sequential so you build knowledge in order.</div> : <><div className="lesson-grid">{c.lessons.map((l,i)=><article key={l}><span>0{i+1}</span><strong>{l}</strong><p>{i < 3 && selectedCourse === 0 ? "Core study material is built in for Version 1. Airline-specific details should come from your official training package." : "This lesson is ready to be populated from your uploaded training package."}</p></article>)}</div><div className="study-actions"><button className="light-btn" onClick={onAI}>Ask AI about this course</button>{selectedCourse === completed && selectedCourse < courses.length && <button className="dark-btn" onClick={onComplete}>I finished this course →</button>}</div></>}</section>; }
function Passport({ courses, completed, events, onHome, onJourney }: { courses:Course[]; completed:number; events:CalendarEvent[]; onHome:()=>void; onJourney:()=>void }) { return <section className="page-section"><Back onClick={onHome} /><div className="passport-cover"><div className="passport-top">CABINREADY <span>TRAINING PASSPORT</span></div><div className="passport-emblem">✈</div><div className="passport-name">FLIGHT ATTENDANT<br />TRAINING</div><div className="passport-id">OCT 2026 · {completed}/8 CHECKPOINTS</div></div><div className="passport-inside"><div><span className="eyebrow">PROGRESS</span><h3>Your training stamps</h3></div><div className="stamp-grid">{courses.map((c,i)=><div key={c.title} className={`stamp ${i<completed?"earned":""}`}><span>{i<completed?"✓":c.icon}</span><small>COURSE {i+1}</small><strong>{c.title}</strong></div>)}</div><div className="weak-box"><div><span className="eyebrow">WORK ON NEXT</span><h3>{completed<8?courses[completed].title:"Final review"}</h3><p>{completed<8?courses[completed].subtitle:"Keep practicing your weaker areas before training day."}</p></div><button className="dark-btn small" onClick={onJourney}>Open journey →</button></div><div className="passport-calendar"><span className="eyebrow">CALENDAR</span><strong>{events.length} planned item{events.length===1?"":"s"}</strong><p>Use your study calendar to keep exams, homework and milestones visible.</p></div></div></section>; }
function PracticeQuestion({ index, answer, onAnswer, onNext }: { index:number; answer:number|null; onAnswer:(i:number)=>void; onNext:()=>void }) { const q=practiceQuestions[index]; return <div className="question-card"><div className="question-meta"><span>UTC / ZULU DRILL</span><span>{index+1}/{practiceQuestions.length}</span></div><h3>{q.q}</h3><div className="option-list">{q.options.map((o,i)=><button key={o} disabled={answer!==null} className={answer===null?"":i===q.answer?"correct":answer===i?"incorrect":"muted"} onClick={()=>onAnswer(i)}>{o}</button>)}</div>{answer!==null && <div className={answer===q.answer?"explanation good":"explanation bad"}><strong>{answer===q.answer?"Correct":"Not quite"}</strong><p>{q.why}</p></div>}<button className="light-btn" onClick={onNext}>Next drill →</button></div>; }
function Flashcards({ cardIndex, flip, setFlip, setIndex, onHome }: { cardIndex:number; flip:boolean; setFlip:(v:boolean)=>void; setIndex:(v:number)=>void; onHome:()=>void }) { const [term,def]=flashcards[cardIndex]; return <section className="page-section"><Back onClick={onHome} /><div className="page-head"><div><span className="eyebrow">MEMORY</span><h2>Flashcards</h2><p>Tap the card to reveal the answer.</p></div></div><button className={`flashcard ${flip?"flipped":""}`} onClick={()=>setFlip(!flip)}><span className="eyebrow">{flip?"ANSWER":"TERM"}</span><strong>{flip?def:term}</strong><small>Tap to flip</small></button><div className="flash-actions"><button className="light-btn" onClick={()=>{setIndex((cardIndex-1+flashcards.length)%flashcards.length);setFlip(false)}}>← Previous</button><span>{cardIndex+1} / {flashcards.length}</span><button className="light-btn" onClick={()=>{setIndex((cardIndex+1)%flashcards.length);setFlip(false)}}>Next →</button></div></section>; }
function Quiz({ title, questions, index, answer, score, onAnswer, onNext, onHome, final }: { title:string; questions:any[]; index:number; answer:number|null; score:number; onAnswer:(i:number)=>void; onNext:()=>void; onHome:()=>void; final?:boolean }) { const q=questions[index]; return <section className="page-section"><Back onClick={onHome} /><div className="page-head"><div><span className="eyebrow">{final?"FINAL CHECK":"QUESTION BANK"}</span><h2>{title}</h2><p>{final?"Your final mixed review. The app will track your result as you work through the set.":"Instant feedback, then an explanation of why the answer is right."}</p></div><span className="count-pill">Score {score}/{questions.length}</span></div><div className="question-card"><div className="question-meta"><span>QUESTION {index+1}</span><span>{questions.length} total</span></div><h3>{q.q}</h3><div className="option-list">{q.options.map((o:string,i:number)=><button key={o} disabled={answer!==null} className={answer===null?"":i===q.answer?"correct":answer===i?"incorrect":"muted"} onClick={()=>onAnswer(i)}>{o}</button>)}</div>{answer!==null&&<div className={answer===q.answer?"explanation good":"explanation bad"}><strong>{answer===q.answer?"Correct":"Incorrect"}</strong><p>{q.why}</p></div>}<button className="dark-btn" onClick={onNext}>{index===questions.length-1?"Restart set":"Next question →"}</button></div></section>; }
