"use client";

import { useEffect, useMemo, useState } from "react";

type Tab = "home" | "journey" | "study" | "passport" | "calendar" | "notes" | "practice" | "flashcards" | "quiz" | "test" | "airports" | "phonetic" | "aircraft" | "training" | "ai" | "profile" | "settings";
type Note = { id:number; text:string; color:string; size:"sm"|"base"|"lg"; bold:boolean };
type EventItem = { id:number; date:string; title:string; type:string; color:string };
type Course = { title:string; subtitle:string; icon:string; lessons:string[] };

const courses:Course[] = [
 {title:"Aviation Foundations",subtitle:"Aircraft, aviation basics & terminology",icon:"✈",lessons:["Cabin crew role & aviation terminology","UTC / Zulu time","IATA airport codes","ICAO phonetic alphabet"]},
 {title:"Emergency Procedures",subtitle:"Safety, evacuation & abnormal situations",icon:"✦",lessons:["Emergency priorities","Evacuation fundamentals","Crew communication","Emergency equipment — official package required"]},
 {title:"Safety & Security",subtitle:"Cabin security, compliance & awareness",icon:"◇",lessons:["Security awareness","Cabin checks","Standardized communication","Airline-specific procedures — official package required"]},
 {title:"Service & Hospitality",subtitle:"Guest experience from boarding to landing",icon:"○",lessons:["Guest experience","Boarding & cabin flow","Service standards","Breeze-specific standards — official package required"]},
 {title:"Onboard Operations",subtitle:"Cabin flow, equipment & procedures",icon:"▱",lessons:["Preflight workflow","Cabin operations","Equipment & procedures","Airline-specific procedures — official package required"]},
 {title:"Medical & First Aid",subtitle:"Recognizing and responding to medical events",icon:"＋",lessons:["Medical response fundamentals","First-aid principles","Communication & escalation","Airline-specific procedures — official package required"]},
 {title:"Breeze Knowledge",subtitle:"Airline-specific policies & standards",icon:"✦",lessons:["Breeze terminology","Company knowledge","Policies & standards","Only verified material from your official training package"]},
 {title:"Final Cabin Check",subtitle:"Mixed review before training day",icon:"✓",lessons:["Mixed review","Weak-area practice","Flashcard review","Final graded knowledge check"]},
];
const airports = [
 ["Akron / Canton","CAK","US"],["Albany","ALB","US"],["Arcata / Eureka","ACV","US"],["Atlantic City","ACY","US"],["Baltimore","BWI","US"],["Bangor","BGR","US"],["Birmingham","BHM","US"],["Brownsville","BRO","US"],["Burbank","BUR","US"],["Burlington","BTV","US"],["Cancún","CUN","INTL"],["Charleston, SC","CHS","US"],["Charleston, WV","CRW","US"],["Cincinnati","CVG","US"],["Columbus","CMH","US"],["Dallas / Fort Worth","DFW","US"],["Dayton","DAY","US"],["Daytona Beach","DAB","US"],["Denver","DEN","US"],["Erie","ERI","US"],["Evansville","EVV","US"],["Fayetteville / Northwest Arkansas","XNA","US"],["Fort Lauderdale","FLL","US"],["Fort Myers","RSW","US"],["Greensboro","GSO","US"],["Greenville / Spartanburg","GSP","US"],["Hartford","BDL","US"],["Huntsville","HSV","US"],["Jacksonville","JAX","US"],["Key West","EYW","US"],["Las Vegas","LAS","US"],["Los Angeles","LAX","US"],["Louisville","SDF","US"],["Manchester","MHT","US"],["Memphis","MEM","US"],["Myrtle Beach","MYR","US"],["Nassau","NAS","INTL"],["New Orleans","MSY","US"],["Newark","EWR","US"],["Norfolk","ORF","US"],["Orlando","MCO","US"],["Pensacola","PNS","US"],["Phoenix","PHX","US"],["Pittsburgh","PIT","US"],["Portland, ME","PWM","US"],["Providence","PVD","US"],["Punta Cana","PUJ","INTL"],["Raleigh / Durham","RDU","US"],["Richmond","RIC","US"],["Rochester","ROC","US"],["San Antonio","SAT","US"],["San Diego","SAN","US"],["San Francisco","SFO","US"],["San José, Costa Rica","SJO","INTL"],["Sarasota / Bradenton","SRQ","US"],["Savannah","SAV","US"],["South Bend","SBN","US"],["St. Thomas","STT","INTL"],["Syracuse","SYR","US"],["Tallahassee","TLH","US"],["Tampa Bay","TPA","US"],["Trenton","TTN","US"],["Vero Beach","VRB","US"],["Washington / Dulles","IAD","US"],["West Palm Beach","PBI","US"],["White Plains","HPN","US"],["Wilmington, NC","ILM","US"]
].map(([city,code,region])=>({city,code,region}));
const phonetic = [["A","Alpha"],["B","Bravo"],["C","Charlie"],["D","Delta"],["E","Echo"],["F","Foxtrot"],["G","Golf"],["H","Hotel"],["I","India"],["J","Juliett"],["K","Kilo"],["L","Lima"],["M","Mike"],["N","November"],["O","Oscar"],["P","Papa"],["Q","Quebec"],["R","Romeo"],["S","Sierra"],["T","Tango"],["U","Uniform"],["V","Victor"],["W","Whiskey"],["X","X-ray"],["Y","Yankee"],["Z","Zulu"]];
const zuluQuestions = [
 {q:"Zulu (Z) is another name for which time reference?",o:["UTC","Eastern Time","Local time","Destination time"],a:0,e:"Zulu is the aviation designation for UTC (UTC±00:00)."},
 {q:"A location is UTC−5. Local time is 14:00. What is Zulu?",o:["09:00Z","14:00Z","19:00Z","05:00Z"],a:2,e:"UTC−5 is five hours behind UTC, so add 5 hours: 14:00 + 5 = 19:00Z."},
 {q:"A location is UTC+3. Local time is 18:00. What is Zulu?",o:["21:00Z","15:00Z","18:00Z","03:00Z"],a:1,e:"UTC+3 is three hours ahead of UTC, so subtract 3 hours: 18:00 − 3 = 15:00Z."},
 {q:"Zulu is 02:00Z and the location is UTC−4. What is local time?",o:["22:00 previous day","06:00","02:00","04:00"],a:0,e:"UTC−4 is four hours behind UTC: 02:00 − 4 = 22:00 on the previous calendar day."}
];
const questions = [
 {q:"What does IAD identify?",o:["Washington Dulles International Airport","Baltimore/Washington International","Newark Liberty International","Long Island MacArthur Airport"],a:0,e:"IAD is the IATA code for Washington Dulles International Airport."},
 {q:"Which word represents A in the ICAO phonetic alphabet?",o:["Alpha","Aviation","Able","Atlas"],a:0,e:"A is Alpha."},
 {q:"Which statement about Zulu is correct?",o:["Zulu is UTC","Zulu is always local time","Zulu is Eastern Time","Zulu changes with daylight saving time"],a:0,e:"Zulu (Z) is the aviation designation for UTC."},
 {q:"What is the best source for Breeze-specific procedures?",o:["Your official training package","A social-media post","A generic quiz website","Another trainee's rumor"],a:0,e:"Airline-specific procedures should be learned from the official training material supplied for your training."},
 {q:"Which aircraft family should CabinReady's aircraft lab be prepared around for your Breeze training?",o:["Airbus A220","Boeing 737","Airbus A380","Embraer 175"],a:0,e:"You identified the Breeze aircraft as the Airbus A220. Exact configuration and equipment locations still need to come from your official training material."}
];
const flashcards = [["UTC","Coordinated Universal Time; the zero-offset reference used for Zulu time."],["Zulu / Z","Aviation designation for UTC. Example: 1530Z = 15:30 UTC."],["IATA code","A three-letter airport identifier such as IAD, MCO or SFO."],["ICAO phonetic alphabet","Alpha, Bravo, Charlie … Zulu."],["Airbus A220","The aircraft family to study in CabinReady; configuration-specific equipment locations must be confirmed from your training package."]];
const noteColors = ["#fffdf8","#f1e5d6","#e2eee0","#e2e8f1","#e5e1ee","#f1dfdf","#eee5c8","#dedfe5"];
const eventColors = ["#d86b6b","#5c7fa6","#71946b","#b28a52","#8c73a7","#5d7773"];
function keyDate(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}

export default function Home(){
 const [tab,setTab]=useState<Tab>("home"); const [splash,setSplash]=useState(true); const [menu,setMenu]=useState(false); const [settings,setSettings]=useState(false);
 const [completed,setCompleted]=useState(0); const [course,setCourse]=useState(0); const [notes,setNotes]=useState<Note[]>([]); const [draft,setDraft]=useState(""); const [editing,setEditing]=useState<number|null>(null);
 const [events,setEvents]=useState<EventItem[]>([]); const [month,setMonth]=useState(new Date(2026,8,1)); const [selectedDay,setSelectedDay]=useState(keyDate(new Date())); const [eventTitle,setEventTitle]=useState(""); const [eventType,setEventType]=useState("Study"); const [eventColor,setEventColor]=useState(eventColors[1]);
 const [qIndex,setQIndex]=useState(0); const [answer,setAnswer]=useState<number|null>(null); const [score,setScore]=useState(0); const [finalStarted,setFinalStarted]=useState(false); const [finalDone,setFinalDone]=useState(false); const [finalScore,setFinalScore]=useState(0);
 const [card,setCard]=useState(0); const [flip,setFlip]=useState(false); const [airportQuery,setAirportQuery]=useState(""); const [pdfName,setPdfName]=useState(""); const [pdfStatus,setPdfStatus]=useState(""); const [pdfResult,setPdfResult]=useState<any>(null); const [aiInput,setAiInput]=useState(""); const [aiResult,setAiResult]=useState(""); const [aiBusy,setAiBusy]=useState(false); const [aiError,setAiError]=useState(""); const [aiEnabled,setAiEnabled]=useState(true);
 const [name,setName]=useState(""); const [username,setUsername]=useState(""); const [signedIn,setSignedIn]=useState(false); const [shared,setShared]=useState<{to:string;note:string}[]>([]);
 useEffect(()=>{const raw=localStorage.getItem("cabinready-v2");if(raw){try{const d=JSON.parse(raw);setCompleted(d.completed||0);setNotes(d.notes||[]);setEvents(d.events||[]);setAiEnabled(d.aiEnabled!==false);setName(d.name||"");setUsername(d.username||"");setSignedIn(!!d.signedIn);setShared(d.shared||[])}catch{}} setTimeout(()=>setSplash(false),900)},[]);
 useEffect(()=>{localStorage.setItem("cabinready-v2",JSON.stringify({completed,notes,events,aiEnabled,name,username,signedIn,shared}))},[completed,notes,events,aiEnabled,name,username,signedIn,shared]);
 const go=(t:Tab)=>{setTab(t);setMenu(false);setSettings(false);window.scrollTo({top:0,behavior:"smooth"})};
 const active=Math.min(completed,7); const filteredAirports=useMemo(()=>airports.filter(a=>`${a.city} ${a.code} ${a.region}`.toLowerCase().includes(airportQuery.toLowerCase())),[airportQuery]);
 const addNote=()=>{if(!draft.trim())return;if(editing!==null)setNotes(ns=>ns.map(n=>n.id===editing?{...n,text:draft.trim()}:n));else setNotes(ns=>[{id:Date.now(),text:draft.trim(),color:noteColors[0],size:"base",bold:false},...ns]);setDraft("");setEditing(null)};
 const addEvent=()=>{if(!eventTitle.trim())return;setEvents(es=>[...es,{id:Date.now(),date:selectedDay,title:eventTitle.trim(),type:eventType,color:eventColor}]);setEventTitle("")};
 const monthDays=()=>{const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:count},(_,i)=>new Date(y,m,i+1))]};
 const answerQ=(i:number)=>{if(answer===null){setAnswer(i);if(i===zuluQuestions[qIndex].a)setScore(s=>s+1)}};
 const nextQ=()=>{setQIndex(i=>(i+1)%zuluQuestions.length);setAnswer(null)};
 const startFinal=()=>{setFinalStarted(true);setFinalDone(false);setQIndex(0);setAnswer(null);setFinalScore(0)};
 const answerFinal=(i:number)=>{if(answer!==null)return;setAnswer(i);if(i===questions[qIndex].a)setFinalScore(s=>s+1)};
 const nextFinal=()=>{if(qIndex===questions.length-1)setFinalDone(true);else{setQIndex(i=>i+1);setAnswer(null)}};
 const uploadPdf=async(file:File)=>{if(!file.name.toLowerCase().endsWith(".pdf")){setAiError("Please choose a PDF training package.");return}if(file.size>50*1024*1024){setAiError("PDFs sent directly to Gemini are limited to 50 MB in this workflow.");return}setPdfName(file.name);setPdfStatus("Uploading and analyzing with Gemini…");setPdfResult(null);setAiError("");const fd=new FormData();fd.append("file",file);try{const r=await fetch("/api/gemini/pdf",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"Gemini could not process the PDF.");setPdfResult(d);setPdfStatus("Ready — the training package was analyzed.")}catch(e){setPdfStatus("");setAiError(e instanceof Error?e.message:"PDF processing failed.")}};
 const askAI=async()=>{if(!aiEnabled){setAiError("AI is turned off in Settings.");return}if(!aiInput.trim())return;setAiBusy(true);setAiError("");try{const r=await fetch("/api/gemini",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:aiInput})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Gemini is not connected.");setAiResult(d.text||"")}catch(e){setAiError(e instanceof Error?e.message:"Gemini request failed.")}finally{setAiBusy(false)}};
 if(splash)return <div className="splash"><div className="splash-plane">✈</div><h1>CabinReady</h1><p>flight attendant training</p><span>PREPARING YOUR CABIN</span></div>;
 return <main className="app-shell"><div className="app-frame"><header className="topbar"><button className="brand" onClick={()=>go("home")}><span className="brand-mark">✈</span><span><strong>CabinReady</strong><small>flight attendant training</small></span></button><div className="top-actions"><span className="date-pill">OCT 2026</span><button className="plane-menu" aria-label="Open main menu" onClick={()=>setMenu(v=>!v)}>✈</button><button className="account-pill" onClick={()=>go("profile")}>{signedIn?"✓ Profile":"Sign in"}</button></div></header>
 {menu&&<div className="main-menu"><div className="menu-title"><span>MAIN MENU</span><button onClick={()=>setMenu(false)}>×</button></div><button onClick={()=>go("home")}>⌂ <span>Home</span></button><button onClick={()=>go("journey")}>✈ <span>Training Journey</span></button><button onClick={()=>go("training")}>▣ <span>Upload Training Package</span></button><button onClick={()=>go("study")}>▤ <span>Study Courses</span></button><button onClick={()=>go("aircraft")}>◉ <span>Aircraft Lab</span></button><button onClick={()=>go("practice")}>◎ <span>Practice Lab</span></button><button onClick={()=>go("flashcards")}>▱ <span>Flashcards</span></button><button onClick={()=>go("quiz")}>? <span>Quiz</span></button><button onClick={()=>go("test")}>✓ <span>Final Test</span></button><button onClick={()=>go("passport")}>▤ <span>Training Passport</span></button><button onClick={()=>go("calendar")}>□ <span>Calendar</span></button><button onClick={()=>go("notes")}>✎ <span>Notes</span></button><button onClick={()=>go("airports")}>⌖ <span>Airport Codes</span></button><button onClick={()=>go("phonetic")}>A <span>Phonetic Alphabet</span></button><button onClick={()=>go("ai")}>✦ <span>CabinReady AI</span></button><button onClick={()=>go("profile")}>○ <span>Profile & Sharing</span></button><button onClick={()=>{setSettings(true);setMenu(false)}}>⚙ <span>Settings</span></button></div>}
 {tab==="home"&&<Home completed={completed} active={active} events={events} go={go} name={name}/>} 
 {tab==="journey"&&<Journey completed={completed} course={course} setCourse={setCourse} go={go}/>} 
 {tab==="study"&&<Study completed={completed} course={course} setCourse={setCourse} complete={()=>setCompleted(c=>Math.min(8,c+1))} go={go}/>} 
 {tab==="passport"&&<Passport completed={completed} events={events} go={go}/>} 
 {tab==="calendar"&&<Calendar month={month} setMonth={setMonth} selectedDay={selectedDay} setSelectedDay={setSelectedDay} events={events} addEvent={addEvent} eventTitle={eventTitle} setEventTitle={setEventTitle} eventType={eventType} setEventType={setEventType} eventColor={eventColor} setEventColor={setEventColor} remove={(id:number)=>setEvents(es=>es.filter(e=>e.id!==id))} monthDays={monthDays}/>} 
 {tab==="notes"&&<Notes notes={notes} draft={draft} setDraft={setDraft} add={addNote} editing={editing} setEditing={setEditing} update={(id:number,p:Partial<Note>)=>setNotes(ns=>ns.map(n=>n.id===id?{...n,...p}:n))} remove={(id:number)=>setNotes(ns=>ns.filter(n=>n.id!==id))} shared={shared} setShared={setShared}/>} 
 {tab==="practice"&&<Practice index={qIndex} answer={answer} score={score} answerQ={answerQ} next={nextQ} go={go}/>} 
 {tab==="flashcards"&&<Flashcards card={card} setCard={setCard} flip={flip} setFlip={setFlip}/>} 
 {tab==="quiz"&&<Quiz go={go}/>} 
 {tab==="test"&&<FinalTest started={finalStarted} done={finalDone} score={finalScore} index={qIndex} answer={answer} start={startFinal} answerQ={answerFinal} next={nextFinal} go={go}/>} 
 {tab==="airports"&&<Airports query={airportQuery} setQuery={setAirportQuery} results={filteredAirports}/>} 
 {tab==="phonetic"&&<Phonetic/>} 
 {tab==="aircraft"&&<Aircraft/>} 
 {tab==="training"&&<TrainingUpload pdfName={pdfName} status={pdfStatus} result={pdfResult} error={aiError} upload={uploadPdf} go={go}/>} 
 {tab==="ai"&&<AI enabled={aiEnabled} input={aiInput} setInput={setAiInput} result={aiResult} error={aiError} busy={aiBusy} ask={askAI}/>} 
 {tab==="profile"&&<Profile name={name} setName={setName} username={username} setUsername={setUsername} signedIn={signedIn} setSignedIn={setSignedIn} shared={shared}/>} 
 {settings&&<Settings enabled={aiEnabled} setEnabled={setAiEnabled} close={()=>setSettings(false)} go={go}/>} 
 <nav className="floating-nav"><button onClick={()=>go("home")}>⌂<span>Home</span></button><button onClick={()=>go("journey")}>✈<span>Journey</span></button><button onClick={()=>go("study")}>▤<span>Study</span></button><button onClick={()=>go("airports")}>⌖<span>Airports</span></button><button onClick={()=>go("notes")}>✎<span>Notes</span></button></nav>
 </div></main>;
}
function Back({go}:{go:()=>void}){return <button className="back-btn" onClick={go}>← Back</button>}
function Home({completed,active,events,go,name}:{completed:number;active:number;events:EventItem[];go:(t:Tab)=>void;name:string}){const today=keyDate(new Date());const todayItems=events.filter(e=>e.date===today);return <section><div className="hero-grid"><div className="hero-copy"><span className="eyebrow">{name?`WELCOME, ${name.toUpperCase()}`:"TRAINING DAY PREP"}</span><h1>Let&apos;s get<br/>cabin-ready.</h1><p className="hero-quote">“You don&apos;t have to know everything today. You just have to keep learning.”</p><button className="dark-btn" onClick={()=>go("practice")}>Start practice →</button></div><div className="hero-card"><span className="mini-label">YOUR NEXT CHECKPOINT</span><div className="hero-course"><span className="plane-badge">✈</span><div><strong>{courses[active].title}</strong><span>{completed}/8 courses completed</span></div></div><div className="mini-route">{courses.map((_,i)=><i key={i} className={i<completed?"done":i===active?"current":""}/>)}</div><button className="text-btn" onClick={()=>go("journey")}>Open training journey →</button></div></div><div className="reminder"><div><span className="eyebrow">TODAY&apos;S REMINDER</span><strong>{todayItems[0]?.title||"Keep your study streak moving."}</strong><p>{todayItems[0]?.type||"Add an exam, homework assignment, study block or training reminder to your calendar."}</p></div><button className="light-btn" onClick={()=>go("calendar")}>Calendar →</button></div><div className="home-grid"><HomeCard title="Study" eyebrow="LEARN" text="Work through the eight-course training route." onClick={()=>go("study")}/><HomeCard title="Training package" eyebrow="SOURCE OF TRUTH" text="Upload your official PDF and let Gemini organize it into your courses." onClick={()=>go("training")}/><HomeCard title="Aircraft Lab" eyebrow="KNOW YOUR AIRCRAFT" text="Study the Airbus A220, cabin zones and equipment as your official package confirms them." onClick={()=>go("aircraft")}/><HomeCard title="Practice" eyebrow="BUILD SKILL" text="Zulu/UTC, airport codes, phonetic alphabet and knowledge drills." onClick={()=>go("practice")}/></div><div className="daily-quote"><span>DAILY NOTE</span><strong>Small study sessions still count. Consistency beats cramming.</strong><button onClick={()=>go("notes")}>Write a note →</button></div></section>}
function HomeCard({eyebrow,title,text,onClick}:{eyebrow:string;title:string;text:string;onClick:()=>void}){return <button className="home-card" onClick={onClick}><span className="eyebrow">{eyebrow}</span><strong>{title}</strong><p>{text}</p><span className="arrow">Open →</span></button>}
function Journey({completed,course,setCourse,go}:{completed:number;course:number;setCourse:(n:number)=>void;go:(t:Tab)=>void}){return <section className="page-section"><Back go={()=>go("home")}/><div className="page-head"><div><span className="eyebrow">TRAINING ROUTE</span><h2>Your journey</h2><p>The aircraft moves forward only when the current course is completed. You cannot mark a locked course complete.</p></div><span className="count-pill">{completed}/8 complete</span></div><div className="journey-map"><div className="route-line"/>{courses.map((c,i)=>{const locked=i>completed;return <button key={c.title} disabled={locked} className={`journey-stop ${course===i?"selected":""}`} onClick={()=>{setCourse(i);go("study")}}><span className="stop-icon">{i<completed?"✓":locked?"•":c.icon}</span><strong>Course {i+1}</strong><b>{c.title}</b><small>{i<completed?"Completed":locked?"Locked":"Current checkpoint"}</small></button>})}</div><div className="aircraft-note"><span>✈</span><div><strong>Aircraft position: Course {Math.min(completed+1,8)}</strong><p>{courses[Math.min(completed,7)].title} is your next checkpoint.</p></div></div></section>}
function Study({completed,course,setCourse,complete,go}:{completed:number;course:number;setCourse:(n:number)=>void;complete:()=>void;go:(t:Tab)=>void}){const c=courses[course];return <section className="page-section"><Back go={()=>go("home")}/><div className="study-tabs">{courses.map((x,i)=><button key={x.title} disabled={i>completed} className={course===i?"selected":""} onClick={()=>setCourse(i)}>C{i+1}</button>)}</div><div className="page-head"><div><span className="eyebrow">COURSE {course+1} OF 8</span><h2>{c.title}</h2><p>{c.subtitle}</p></div><span className="count-pill">{course<completed?"Completed":course===completed?"Current":"Locked"}</span></div>{course>completed?<div className="locked-panel">Finish Course {course} first. The journey is intentionally sequential.</div>:<><div className="lesson-grid">{c.lessons.map((l,i)=><button className="lesson-card" key={l} onClick={()=>go(course===0&&i===1?"practice":"training")}><span>0{i+1}</span><strong>{l}</strong><p>{course===0?"Built-in foundation lesson. Click to practice or explore the source material.":"This lesson is ready to be populated from your official training package. Upload it in Training Package."}</p><b>Open lesson →</b></button>)}</div><div className="study-actions"><button className="light-btn" onClick={()=>go("training")}>Open training package</button>{course===completed&&course<8&&<button className="dark-btn" onClick={complete}>Complete Course {course+1} →</button>}</div></>}</section>}
function Passport({completed,events,go}:{completed:number;events:EventItem[];go:(t:Tab)=>void}){return <section className="page-section"><Back go={()=>go("home")}/><div className="passport-cover"><div className="passport-top">CABINREADY <span>TRAINING PASSPORT</span></div><div className="passport-emblem">✈</div><div className="passport-name">FLIGHT ATTENDANT<br/>TRAINING</div><div className="passport-id">OCT 2026 · {completed}/8 CHECKPOINTS</div></div><div className="passport-inside"><span className="eyebrow">TRAINING STAMPS</span><h3>Your progress</h3><div className="stamp-grid">{courses.map((c,i)=><div className={`stamp ${i<completed?"earned":""}`} key={c.title}><span>{i<completed?"✓":c.icon}</span><small>COURSE {i+1}</small><strong>{c.title}</strong></div>)}</div><div className="weak-box"><div><span className="eyebrow">WORK ON NEXT</span><h3>{completed<8?courses[completed].title:"Final review"}</h3><p>{completed<8?courses[completed].subtitle:"Keep practicing weaker areas."}</p></div><button className="dark-btn small" onClick={()=>go("journey")}>Open journey →</button></div><div className="passport-calendar"><span className="eyebrow">PLANNER</span><strong>{events.length} scheduled item{events.length===1?"":"s"}</strong><p>Calendar items stay visible here as a quick reminder.</p></div></div></section>}
function Calendar({month,setMonth,selectedDay,setSelectedDay,events,addEvent,eventTitle,setEventTitle,eventType,setEventType,eventColor,setEventColor,remove,monthDays}:{month:Date;setMonth:(d:Date)=>void;selectedDay:string;setSelectedDay:(s:string)=>void;events:EventItem[];addEvent:()=>void;eventTitle:string;setEventTitle:(s:string)=>void;eventType:string;setEventType:(s:string)=>void;eventColor:string;setEventColor:(s:string)=>void;remove:(id:number)=>void;monthDays:()=>Array<Date|null>}){const selected=events.filter(e=>e.date===selectedDay);return <section className="page-section"><div className="page-head"><div><span className="eyebrow">STAY ON TRACK</span><h2>Study calendar</h2><p>Color-code exams, homework, study sessions and training reminders.</p></div></div><div className="calendar-wrap"><div className="calendar-head"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>←</button><strong>{month.toLocaleString("en-US",{month:"long",year:"numeric"})}</strong><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>→</button></div><div className="weekday">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{monthDays().map((d,i)=>d?<button key={i} onClick={()=>setSelectedDay(keyDate(d))} className={selectedDay===keyDate(d)?"selected-day":""}><span>{d.getDate()}</span>{events.filter(e=>e.date===keyDate(d)).slice(0,2).map(e=><small key={e.id} style={{background:e.color}}>{e.type}</small>)}</button>:<div key={i}/>)}</div></div><div className="event-panel"><span className="eyebrow">{selectedDay}</span><h3>Plan your day</h3><div className="event-form"><input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Exam, homework, study…"/><select value={eventType} onChange={e=>setEventType(e.target.value)}><option>Study</option><option>Exam</option><option>Homework</option><option>Training</option><option>Reminder</option></select><div className="color-picker">{eventColors.map(c=><button key={c} aria-label="calendar color" onClick={()=>setEventColor(c)} style={{background:c,border:eventColor===c?"3px solid #25231f":"1px solid transparent"}}/>)}</div><button className="dark-btn small" onClick={addEvent}>Add</button></div>{selected.length>0&&<div className="event-list">{selected.map(e=><div key={e.id}><span style={{background:e.color}}>{e.type}</span><strong>{e.title}</strong><button onClick={()=>remove(e.id)}>×</button></div>)}</div>}</div></section>}
function Notes({notes,draft,setDraft,add,editing,setEditing,update,remove,shared,setShared}:{notes:Note[];draft:string;setDraft:(s:string)=>void;add:()=>void;editing:number|null;setEditing:(n:number|null)=>void;update:(id:number,p:Partial<Note>)=>void;remove:(id:number)=>void;shared:{to:string;note:string}[];setShared:(x:{to:string;note:string}[])=>void}){const [shareUser,setShareUser]=useState("");const [shareNote,setShareNote]=useState("");return <section className="page-section"><div className="page-head"><div><span className="eyebrow">REMEMBER</span><h2>My notes</h2><p>Write, edit, resize, bold and color-code the things you need to remember.</p></div></div><div className="note-editor"><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Write a note…"/><div className="editor-actions"><button className="dark-btn small" onClick={add}>{editing!==null?"Save changes":"Add note"}</button>{editing!==null&&<button className="light-btn" onClick={()=>{setEditing(null);setDraft("")}}>Cancel</button>}</div></div><div className="notes-list">{notes.length===0?<div className="empty">Your saved notes will appear here.</div>:notes.map(n=><article className="note-card" style={{background:n.color}} key={n.id}><div className={`note-text note-${n.size} ${n.bold?"note-bold":""}`}>{n.text}</div><div className="note-controls"><button onClick={()=>update(n.id,{bold:!n.bold})}>B</button><button onClick={()=>update(n.id,{size:n.size==="sm"?"base":n.size==="base"?"lg":"sm"})}>A↕</button>{noteColors.map(c=><button key={c} aria-label="note color" style={{background:c}} onClick={()=>update(n.id,{color:c})}/>) }<button onClick={()=>{setEditing(n.id);setDraft(n.text);window.scrollTo({top:0,behavior:"smooth"})}}>Edit</button><button onClick={()=>remove(n.id)}>Delete</button></div></article>)}</div><div className="share-panel"><span className="eyebrow">TRAINEE NOTE SHARING</span><h3>Share a note by username</h3><p>Version 1 stores the share request locally. Cross-device sharing will be connected when account/database authentication is added.</p><div className="share-form"><input value={shareUser} onChange={e=>setShareUser(e.target.value)} placeholder="@username"/><select value={shareNote} onChange={e=>setShareNote(e.target.value)}><option value="">Choose a note</option>{notes.map(n=><option key={n.id} value={n.text}>{n.text.slice(0,45)}</option>)}</select><button className="dark-btn small" onClick={()=>{if(shareUser&&shareNote){setShared([...shared,{to:shareUser,note:shareNote}]);setShareUser("");setShareNote("")}}}>Share</button></div></div></section>}
function Practice({index,answer,score,answerQ,next,go}:{index:number;answer:number|null;score:number;answerQ:(i:number)=>void;next:()=>void;go:(t:Tab)=>void}){const q=zuluQuestions[index];return <section className="page-section"><div className="page-head"><div><span className="eyebrow">BUILD SKILL</span><h2>Practice lab</h2><p>UTC/Zulu calculations with instant explanations. Remember: local = UTC + offset, so to find Zulu from local time, subtract a positive UTC offset and add a negative one.</p></div><span className="count-pill">{score} correct</span></div><div className="tool-grid"><button className="tool-card active"><strong>UTC / Zulu</strong><p>Calculate both directions.</p></button><button className="tool-card" onClick={()=>go("airports")}><strong>Airport codes</strong><p>Search the network.</p></button><button className="tool-card" onClick={()=>go("phonetic")}><strong>Phonetic</strong><p>Alpha through Zulu.</p></button><button className="tool-card" onClick={()=>go("quiz")}><strong>Question bank</strong><p>Mixed practice.</p></button></div><QuestionCard q={q.q} options={q.o} answer={answer} correct={q.a} explanation={q.e} onAnswer={answerQ} onNext={next} label="UTC / ZULU DRILL" count={`${index+1}/${zuluQuestions.length}`}/></section>}
function QuestionCard({q,options,answer,correct,explanation,onAnswer,onNext,label,count}:{q:string;options:string[];answer:number|null;correct:number;explanation:string;onAnswer:(i:number)=>void;onNext:()=>void;label:string;count:string}){return <div className="question-card"><div className="question-meta"><span>{label}</span><span>{count}</span></div><h3>{q}</h3><div className="option-list">{options.map((o,i)=><button disabled={answer!==null} className={answer===null?"":i===correct?"correct":answer===i?"incorrect":"muted"} key={o} onClick={()=>onAnswer(i)}>{o}</button>)}</div>{answer!==null&&<div className={answer===correct?"explanation good":"explanation bad"}><strong>{answer===correct?"Correct":"Not quite"}</strong><p>{explanation}</p></div>}<button className="light-btn" onClick={onNext}>Next drill →</button></div>}
function Flashcards({card,setCard,flip,setFlip}:{card:number;setCard:(n:number)=>void;flip:boolean;setFlip:(b:boolean)=>void}){const [term,def]=flashcards[card];return <section className="page-section"><div className="page-head"><div><span className="eyebrow">MEMORY</span><h2>Flashcards</h2><p>Tap to flip. Move through the deck until the answers feel automatic.</p></div></div><button className="flashcard" onClick={()=>setFlip(!flip)}><span className="eyebrow">{flip?"ANSWER":"TERM"}</span><strong>{flip?def:term}</strong><small>Tap to flip</small></button><div className="flash-actions"><button className="light-btn" onClick={()=>{setCard((card-1+flashcards.length)%flashcards.length);setFlip(false)}}>← Previous</button><span>{card+1}/{flashcards.length}</span><button className="light-btn" onClick={()=>{setCard((card+1)%flashcards.length);setFlip(false)}}>Next →</button></div></section>}
function Quiz({go}:{go:(t:Tab)=>void}){const [i,setI]=useState(0);const [a,setA]=useState<number|null>(null);const [s,setS]=useState(0);const q=questions[i];const choose=(n:number)=>{if(a===null){setA(n);if(n===q.a)setS(x=>x+1)}};const next=()=>{setI((i+1)%questions.length);setA(null)};return <section className="page-section"><div className="page-head"><div><span className="eyebrow">QUESTION BANK</span><h2>Practice quiz</h2><p>Instant feedback and explanations.</p></div><span className="count-pill">Score {s}/{questions.length}</span></div><QuestionCard q={q.q} options={q.o} answer={a} correct={q.a} explanation={q.e} onAnswer={choose} onNext={next} label="KNOWLEDGE QUIZ" count={`${i+1}/${questions.length}`}/><button className="text-btn center-btn" onClick={()=>go("flashcards")}>Need a memory refresher? Open flashcards →</button></section>}
function FinalTest({started,done,score,index,answer,start,answerQ,next,go}:{started:boolean;done:boolean;score:number;index:number;answer:number|null;start:()=>void;answerQ:(i:number)=>void;next:()=>void;go:(t:Tab)=>void}){if(!started)return <section className="page-section"><div className="test-intro"><span className="eyebrow">FINAL CHECK</span><h2>Final cabin test</h2><p>This test is intentionally graded so your brain gets used to seeing a score before training.</p><button className="dark-btn" onClick={start}>Start graded test →</button></div></section>;if(done)return <section className="page-section"><div className="test-result"><span className="eyebrow">TEST COMPLETE</span><h2>{score}/{questions.length}</h2><p>{Math.round(score/questions.length*100)}% — review missed questions before restarting.</p><button className="dark-btn" onClick={start}>Retake test</button><button className="light-btn" onClick={()=>go("practice")}>Practice weak areas</button></div></section>;const q=questions[index];return <section className="page-section"><div className="page-head"><div><span className="eyebrow">GRADED FINAL TEST</span><h2>Final cabin check</h2></div><span className="count-pill">Score {score}/{questions.length}</span></div><QuestionCard q={q.q} options={q.o} answer={answer} correct={q.a} explanation={q.e} onAnswer={answerQ} onNext={next} label="GRADED" count={`${index+1}/${questions.length}`}/></section>}
function Airports({query,setQuery,results}:{query:string;setQuery:(s:string)=>void;results:any[]}){return <section className="page-section"><div className="page-head"><div><span className="eyebrow">BREEZE NETWORK</span><h2>Airport codes</h2><p>Search by city or IATA code. This list is a study reference; verify the current Breeze network against official company material.</p></div><span className="count-pill">{results.length} shown</span></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search airport or code…"/><div className="airport-grid">{results.map(a=><div className="airport-card" key={a.code}><span>{a.region}</span><strong>{a.code}</strong><div>{a.city}</div></div>)}</div></section>}
function Phonetic(){return <section className="page-section"><div className="page-head"><div><span className="eyebrow">COMMUNICATION</span><h2>ICAO phonetic alphabet</h2><p>Learn the standardized spelling alphabet from Alpha through Zulu.</p></div></div><div className="phonetic-grid">{phonetic.map(([l,w])=><div key={l}><strong>{l}</strong><span>{w}</span></div>)}</div></section>}
function Aircraft(){const [selected,setSelected]=useState("Cabin");const zones=["Cockpit","Forward galley","Cabin","Mid-cabin","Aft galley","Lavatory / service areas","Exit rows","Overhead / emergency equipment"];return <section className="page-section"><div className="page-head"><div><span className="eyebrow">KNOW YOUR AIRCRAFT</span><h2>Airbus A220 lab</h2><p>Interactive study shell for the Airbus A220. Exact seat rows, equipment positions and configuration details must be populated from your official Breeze training package rather than guessed.</p></div></div><div className="aircraft-layout"><div className="aircraft-visual"><div className="wing left"/><div className="wing right"/><div className="fuselage"><div className="nose">✈</div>{zones.map((z,i)=><button key={z} className={selected===z?"zone selected":"zone"} onClick={()=>setSelected(z)}><span>{i+1}</span>{z}</button>)}<div className="tail">▴</div></div></div><div className="aircraft-info"><span className="eyebrow">SELECTED ZONE</span><h3>{selected}</h3><p>When your study package is uploaded, CabinReady will use its verified information here.</p><div className="equipment-list"><div><strong>🧯 Fire extinguisher</strong><span>Location: training-package dependent</span></div><div><strong>🫁 Oxygen equipment</strong><span>Location: training-package dependent</span></div><div><strong>⚡ AED / medical equipment</strong><span>Presence and location: training-package dependent</span></div><div><strong>🚪 Emergency exits</strong><span>Seat rows and door assignments: training-package dependent</span></div></div></div></div><div className="notice">CabinReady will not invent an equipment location or seat-row assignment. Those details are safety-critical and should be sourced from the official Breeze training package.</div></section>}
function TrainingUpload({pdfName,status,result,error,upload,go}:{pdfName:string;status:string;result:any;error:string;upload:(f:File)=>void;go:(t:Tab)=>void}){return <section className="page-section"><div className="page-head"><div><span className="eyebrow">SOURCE OF TRUTH</span><h2>Training package</h2><p>This is the dedicated upload area. Your official PDF is what will make the course content airline-specific.</p></div></div><label className="upload-box large"><input type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><span className="upload-icon">↑</span><strong>{pdfName||"Upload your official Breeze training PDF"}</strong><small>Gemini can read PDF documents; direct PDF input is limited to 50 MB in this workflow. The file is processed server-side.</small><span className="dark-btn small">Choose PDF</span></label>{status&&<div className="status-box">{status}</div>}{error&&<div className="error-box">{error}</div>}{result&&<div className="analysis-box"><span className="eyebrow">GEMINI ANALYSIS</span><h3>Training map created</h3><p>{result.summary}</p><div className="course-map">{(result.courses||[]).map((c:any)=><div key={c.course}><strong>Course {c.course}: {c.title}</strong><span>{c.reason}</span></div>)}</div><button className="dark-btn small" onClick={()=>go("study")}>Open study courses →</button></div>}<div className="notice">The app will use the uploaded material to create course summaries, questions and flashcards. It will not replace official training or invent missing Breeze-specific procedures.</div></section>}
function AI({enabled,input,setInput,result,error,busy,ask}:{enabled:boolean;input:string;setInput:(s:string)=>void;result:string;error:string;busy:boolean;ask:()=>void}){return <section className="page-section"><div className="page-head"><div><span className="eyebrow">OPTIONAL AI</span><h2>CabinReady AI</h2><p>Powered by Gemini when enabled. Turn it off in Settings whenever you want an all-brains study session.</p></div><span className="ai-badge">{enabled?"GEMINI ON":"AI OFF"}</span></div><div className="ai-chat full"><textarea disabled={!enabled} value={input} onChange={e=>setInput(e.target.value)} placeholder={enabled?"Ask: Explain UTC−5 to me like I’m learning it for the first time…":"AI is turned off in Settings."}/><button className="dark-btn" disabled={!enabled||busy} onClick={ask}>{busy?"Thinking…":"Ask Gemini →"}</button></div>{error&&<div className="error-box">{error}</div>}{result&&<div className="ai-response"><span className="eyebrow">GEMINI</span><p>{result}</p></div>}</section>}
function Profile({name,setName,username,setUsername,signedIn,setSignedIn,shared}:{name:string;setName:(s:string)=>void;username:string;setUsername:(s:string)=>void;signedIn:boolean;setSignedIn:(b:boolean)=>void;shared:{to:string;note:string}[]}){return <section className="page-section"><div className="page-head"><div><span className="eyebrow">YOUR ACCOUNT</span><h2>Profile</h2><p>Personalize CabinReady and prepare the account layer for cross-device progress.</p></div></div><div className="profile-card"><label>Display name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value.replace(/\s/g,""))} placeholder="@yourusername"/></label><div className="auth-buttons"><button className="light-btn" onClick={()=>setSignedIn(true)}> Continue with Apple</button><button className="light-btn" onClick={()=>setSignedIn(true)}>G Continue with Google</button></div><div className={signedIn?"status-box":"notice"}>{signedIn?"Profile session is active on this browser. Cross-device cloud sync needs the production authentication/database connection.":"Sign in to prepare your profile. Apple/Google buttons are UI-ready; production OAuth credentials still need to be connected."}</div></div>{shared.length>0&&<div className="share-panel"><span className="eyebrow">SHARED</span><h3>Notes you sent</h3>{shared.map((s,i)=><div className="shared-note" key={i}><strong>{s.to}</strong><span>{s.note}</span></div>)}</div>}</section>}
function Settings({enabled,setEnabled,close,go}:{enabled:boolean;setEnabled:(b:boolean)=>void;close:()=>void;go:(t:Tab)=>void}){return <div className="settings-overlay"><div className="settings-panel"><div className="settings-head"><div><span className="eyebrow">SETTINGS</span><h3>CabinReady controls</h3></div><button onClick={close}>×</button></div><div className="setting-row"><div><strong>Gemini AI</strong><p>Turn the AI study assistant on or off.</p></div><button className={`toggle ${enabled?"on":""}`} onClick={()=>setEnabled(!enabled)}><span/></button></div><button className="setting-link" onClick={()=>{close();go("profile")}}>Profile & sign-in <span>→</span></button><button className="setting-link" onClick={()=>{close();go("training")}}>Training package <span>→</span></button></div></div>}
