"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";

type Tab =
  | "home" | "training" | "journey" | "study" | "passport" | "calendar"
  | "notes" | "practice" | "flashcards" | "quiz" | "test" | "airports"
  | "phonetic" | "aircraft" | "package" | "profile" | "settings" | "ai";

type Note = { id: number; title: string; text: string; color: string; size: "sm" | "base" | "lg"; bold: boolean };
type EventItem = { id: number; date: string; title: string; type: string; color: string };
type Question = { q: string; o: string[]; a: number; e: string; topic: string };
type Course = { title: string; subtitle: string; lessons: { title: string; body: string }[] };

const courses: Course[] = [
  { title: "Aviation Foundations", subtitle: "Aircraft, aviation basics & terminology", lessons: [
    { title: "Cabin Crew Role", body: "Core responsibilities, professionalism, communication and the purpose of the cabin crew role. Airline-specific duties must be confirmed against the official training package." },
    { title: "UTC & Zulu Time", body: "Learn the relationship between UTC and Zulu time, UTC offsets, local-time conversion and date changes across midnight." },
    { title: "IATA Airport Codes", body: "Build recognition of three-letter airport identifiers used in airline operations." },
    { title: "ICAO Phonetic Alphabet", body: "Practice Alpha through Zulu so letters can be communicated clearly in aviation contexts." },
  ]},
  { title: "Emergency Procedures", subtitle: "Safety, evacuation & abnormal situations", lessons: [
    { title: "Emergency Priorities", body: "Study the fundamentals of recognizing an emergency and following the correct training sequence." },
    { title: "Evacuation Fundamentals", body: "Review evacuation concepts and terminology. Exact procedures belong to the official training package." },
    { title: "Crew Communication", body: "Practice clear, standardized communication and escalation concepts." },
    { title: "Emergency Equipment", body: "Equipment identification and exact locations will be populated from your official training package." },
  ]},
  { title: "Safety & Security", subtitle: "Cabin security, compliance & awareness", lessons: [
    { title: "Security Awareness", body: "Study security concepts and the importance of situational awareness." },
    { title: "Cabin Checks", body: "Review the purpose and sequence of cabin checks using verified training material." },
    { title: "Standardized Communication", body: "Build familiarity with concise operational communication." },
    { title: "Airline-Specific Procedures", body: "Reserved for verified material from your official training package." },
  ]},
  { title: "Service & Hospitality", subtitle: "Guest experience from boarding to landing", lessons: [
    { title: "Guest Experience", body: "Study professional service, communication and passenger care concepts." },
    { title: "Boarding & Cabin Flow", body: "Understand the flow of boarding and the cabin environment." },
    { title: "Service Standards", body: "Review service principles and terminology. Exact Breeze standards require the official package." },
    { title: "Breeze-Specific Standards", body: "This lesson is a destination for verified training-package content only." },
  ]},
  { title: "Onboard Operations", subtitle: "Cabin flow, equipment & procedures", lessons: [
    { title: "Preflight Workflow", body: "Learn the purpose of preflight preparation and organized cabin readiness." },
    { title: "Cabin Operations", body: "Review the operational flow of the cabin." },
    { title: "Equipment & Procedures", body: "Use the equipment and procedures content from your official package." },
    { title: "Airline-Specific Operations", body: "Reserved for verified Breeze material." },
  ]},
  { title: "Medical & First Aid", subtitle: "Recognizing and responding to medical events", lessons: [
    { title: "Medical Response Fundamentals", body: "Study general recognition, communication and response concepts." },
    { title: "First-Aid Principles", body: "Review general first-aid concepts. Training-specific instructions must come from the official package." },
    { title: "Communication & Escalation", body: "Practice concise reporting and escalation concepts." },
    { title: "Airline-Specific Medical Procedures", body: "Reserved for verified training-package material." },
  ]},
  { title: "Breeze Knowledge", subtitle: "Airline-specific policies & standards", lessons: [
    { title: "Breeze Terminology", body: "A dedicated place for verified company terminology from your training package." },
    { title: "Company Knowledge", body: "Upload your package and place verified company knowledge here." },
    { title: "Policies & Standards", body: "Only confirmed material belongs in this section." },
    { title: "Official Training Package", body: "This section deliberately avoids invented airline-specific information." },
  ]},
  { title: "Final Cabin Check", subtitle: "Mixed review before training day", lessons: [
    { title: "Mixed Review", body: "Review questions across the study system." },
    { title: "Weak-Area Practice", body: "Focus on topics where your quiz and practice scores need improvement." },
    { title: "Flashcard Review", body: "Use active recall before the final assessment." },
    { title: "Final Graded Knowledge Check", body: "A scored test that records your percentage and shows missed answers." },
  ]},
];

const airports = [["Akron / Canton","CAK"],["Albany","ALB"],["Arcata / Eureka","ACV"],["Atlantic City","ACY"],["Baltimore","BWI"],["Bangor","BGR"],["Birmingham","BHM"],["Brownsville","BRO"],["Burbank","BUR"],["Burlington","BTV"],["Cancún","CUN"],["Charleston, SC","CHS"],["Cincinnati","CVG"],["Columbus","CMH"],["Dallas / Fort Worth","DFW"],["Denver","DEN"],["Fort Lauderdale","FLL"],["Fort Myers","RSW"],["Greensboro","GSO"],["Hartford","BDL"],["Jacksonville","JAX"],["Las Vegas","LAS"],["Los Angeles","LAX"],["Louisville","SDF"],["Manchester","MHT"],["Memphis","MEM"],["Nassau","NAS"],["New Orleans","MSY"],["Newark","EWR"],["Norfolk","ORF"],["Orlando","MCO"],["Pensacola","PNS"],["Phoenix","PHX"],["Pittsburgh","PIT"],["Portland, ME","PWM"],["Providence","PVD"],["Punta Cana","PUJ"],["Raleigh / Durham","RDU"],["Richmond","RIC"],["Rochester","ROC"],["San Antonio","SAT"],["San Diego","SAN"],["San Francisco","SFO"],["San José, Costa Rica","SJO"],["Sarasota / Bradenton","SRQ"],["Savannah","SAV"],["South Bend","SBN"],["St. Thomas","STT"],["Syracuse","SYR"],["Tallahassee","TLH"],["Tampa Bay","TPA"],["Trenton","TTN"],["Vero Beach","VRB"],["Washington / Dulles","IAD"],["West Palm Beach","PBI"],["White Plains","HPN"],["Wilmington, NC","ILM"],].map(([city,code])=>({city,code}));
const phonetic=[["A","Alpha"],["B","Bravo"],["C","Charlie"],["D","Delta"],["E","Echo"],["F","Foxtrot"],["G","Golf"],["H","Hotel"],["I","India"],["J","Juliett"],["K","Kilo"],["L","Lima"],["M","Mike"],["N","November"],["O","Oscar"],["P","Papa"],["Q","Quebec"],["R","Romeo"],["S","Sierra"],["T","Tango"],["U","Uniform"],["V","Victor"],["W","Whiskey"],["X","X-ray"],["Y","Yankee"],["Z","Zulu"]];
const questions:Question[]=[
 {q:"Zulu (Z) is another name for which time reference?",o:["UTC","Eastern Time","Local time","Destination time"],a:0,e:"Zulu is the aviation designation for UTC (UTC±00:00).",topic:"UTC / Zulu"},
 {q:"A location is UTC−5. Local time is 14:00. What is Zulu?",o:["09:00Z","14:00Z","19:00Z","05:00Z"],a:2,e:"UTC−5 is five hours behind UTC, so add five hours to local time: 14:00 + 5 = 19:00Z.",topic:"UTC / Zulu"},
 {q:"A location is UTC+3. Local time is 18:00. What is Zulu?",o:["21:00Z","15:00Z","18:00Z","03:00Z"],a:1,e:"UTC+3 is three hours ahead of UTC, so subtract three hours: 18:00 − 3 = 15:00Z.",topic:"UTC / Zulu"},
 {q:"Zulu is 02:00Z and the location is UTC−4. What is local time?",o:["22:00 previous day","06:00","02:00","04:00"],a:0,e:"UTC−4 is four hours behind UTC: 02:00 − 4 = 22:00 on the previous calendar day.",topic:"UTC / Zulu"},
 {q:"Which word represents A in the ICAO phonetic alphabet?",o:["Alpha","Aviation","Able","Atlas"],a:0,e:"A is represented by Alpha.",topic:"Phonetic Alphabet"},
 {q:"Which word represents J in the ICAO phonetic alphabet?",o:["Jupiter","Juliett","Jet","January"],a:1,e:"J is represented by Juliett.",topic:"Phonetic Alphabet"},
 {q:"What does IAD identify?",o:["Washington Dulles International Airport","Baltimore/Washington International","Newark Liberty International","Long Island MacArthur Airport"],a:0,e:"IAD is the IATA code for Washington Dulles International Airport.",topic:"Airport Codes"},
 {q:"What does MCO identify?",o:["Miami International","Orlando International","Memphis International","Manchester-Boston Regional"],a:1,e:"MCO is the IATA code for Orlando International Airport.",topic:"Airport Codes"},
 {q:"What does SFO identify?",o:["San Diego International","San Francisco International","Sacramento International","Santa Fe Regional"],a:1,e:"SFO is the IATA code for San Francisco International Airport.",topic:"Airport Codes"},
 {q:"Which aircraft family is the focus of the aircraft lab?",o:["Airbus A220","Boeing 737","Airbus A380","Embraer 175"],a:0,e:"The study system uses the Airbus A220 as the study model. Exact cabin layout and equipment locations must be verified against the official training package.",topic:"Aircraft"},
 {q:"What should be the primary source for Breeze-specific procedures?",o:["Your official training package","A social-media post","A generic quiz website","Another trainee's rumor"],a:0,e:"Airline-specific procedures should be learned from the official material supplied for your training.",topic:"Breeze Knowledge"},
 {q:"Which direction means a positive UTC offset?",o:["Local time is ahead of UTC","Local time is behind UTC","It always means midnight","It means the airport is west"],a:0,e:"UTC+ means local time is ahead of UTC; to convert local time to UTC, subtract the positive offset.",topic:"UTC / Zulu"},
 {q:"Which letter is represented by Bravo?",o:["A","B","C","D"],a:1,e:"Bravo is B in the ICAO phonetic alphabet.",topic:"Phonetic Alphabet"},
 {q:"Which airport uses the code BWI?",o:["Baltimore/Washington","Boston Logan","Birmingham","Buffalo"],a:0,e:"BWI identifies Baltimore/Washington International Thurgood Marshall Airport.",topic:"Airport Codes"},
 {q:"What is the best approach when a study topic is airline-specific but the official package has not been uploaded?",o:["Leave it unverified until the official package is available","Guess from social media","Copy another trainee","Invent a likely procedure"],a:0,e:"CabinReady should clearly separate verified training content from general study material.",topic:"Breeze Knowledge"},
];
const flashcards=[["UTC","Coordinated Universal Time; the zero-offset reference used for Zulu time."],["Zulu / Z","The aviation designation for UTC. Example: 1530Z means 15:30 UTC."],["Local → UTC","Subtract the local UTC offset. UTC−5 means add 5 hours to local time; UTC+3 means subtract 3 hours."],["UTC → Local","Add the local UTC offset. Watch the date when crossing midnight."],["IATA code","A three-letter airport identifier such as IAD, MCO or SFO."],["ICAO phonetic alphabet","Alpha, Bravo, Charlie … Zulu. Used to spell letters clearly over radio/telephone communications."],["Airbus A220","The aircraft family used as the study model. Exact cabin layout and equipment locations require official training material."]];
const noteColors=["#fffdf8","#e9dfd2","#dce8f0","#e1e7de","#e7e0ee","#f0dddd","#e9e1c9","#dfe2e7","#d8e7e5","#e5d9cf","#d8dfe9","#ead9d4","#d7e3ef","#e4d9d0"]; const eventColors=["#c94f58","#5f82ad","#738e69","#b18a4f","#8b72a7","#e17b3a","#4f7774"]; const eventTypes=["Study","Homework","Exam","Training","Graduation","Reminder"];
const dailyQuotes=["You do not have to know everything today. Keep learning, practicing, and moving.","Confidence is built one practiced answer at a time.","Study the small details now so training day feels familiar later.","Progress counts even when the lesson feels difficult.","Practice turns unfamiliar information into something you can recall.","You are building a skill, not chasing perfection.","Read it. Recall it. Practice it. Repeat it.","Small study sessions add up to real preparation."];
const menuItems:{id:Tab;label:string;icon:string;desc?:string}[]=[{id:"home",label:"Home",icon:"⌂",desc:"Dashboard & reminders"},{id:"training",label:"Training Hub",icon:"✦",desc:"Your training command center"},{id:"package",label:"Training Package",icon:"▣",desc:"Upload and manage your package"},{id:"journey",label:"Training Journey",icon:"➜",desc:"Courses & lessons"},{id:"study",label:"Study Center",icon:"▤",desc:"Core study topics"},{id:"practice",label:"Practice Lab",icon:"◉",desc:"UTC/Zulu and skill practice"},{id:"quiz",label:"Quiz",icon:"?",desc:"Instant scored practice"},{id:"test",label:"Final Test",icon:"✓",desc:"Graded final knowledge check"},{id:"flashcards",label:"Flashcards",icon:"▤",desc:"Active recall"},{id:"aircraft",label:"Aircraft Lab",icon:"✈",desc:"Interactive A220 study model"},{id:"passport",label:"Training Passport",icon:"▥",desc:"Your progress passport"},{id:"calendar",label:"Calendar",icon:"□",desc:"Color-coded study plan"},{id:"notes",label:"Notes",icon:"✎",desc:"Editable study notes"},{id:"airports",label:"Airport Codes",icon:"⌖",desc:"IATA code practice"},{id:"phonetic",label:"Phonetic Alphabet",icon:"ABC",desc:"Alpha through Zulu"},{id:"ai",label:"AI Study Help",icon:"✧",desc:"Optional AI assistance"},{id:"profile",label:"Profile",icon:"○",desc:"Name, username & account"},{id:"settings",label:"Settings",icon:"⚙",desc:"AI and offline controls"}];
const defaultEvents:EventItem[]=[{id:1,date:"2026-09-05",title:"Day 1 of training",type:"Training",color:eventColors[1]},{id:2,date:"2026-09-12",title:"Review UTC & Zulu",type:"Study",color:eventColors[0]}];
function todayString(){return new Date().toISOString().slice(0,10)} function formatDate(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})} function readJson<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function usePersistentState<T>(key:string,initial:T){const [value,setValue]=useState<T>(initial);const [ready,setReady]=useState(false);useEffect(()=>{setValue(readJson(key,initial));setReady(true)},[key]);useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(value))},[key,value,ready]);return [value,setValue] as const}

export default function CabinReady(){
 const [tab,setTab]=useState<Tab>("home");const [menuOpen,setMenuOpen]=useState(false);const [profile,setProfile]=usePersistentState("cr-profile",{name:"",username:""});const [events,setEvents]=usePersistentState<EventItem[]>("cr-events",defaultEvents);const [notes,setNotes]=usePersistentState<Note[]>("cr-notes",[]);const [completed,setCompleted]=usePersistentState<Record<string,boolean>>("cr-completed",{});const [settings,setSettings]=usePersistentState("cr-settings",{aiEnabled:false,offline:false});const [packageInfo,setPackageInfo]=usePersistentState<{name:string;size:number;pages:number;date:string}|null>("cr-package",null);
 const [selectedLesson,setSelectedLesson]=useState<{course:number;lesson:number}|null>(null);const [selectedNote,setSelectedNote]=useState<number|null>(null);const [noteDraft,setNoteDraft]=useState({title:"",text:"",color:noteColors[0],size:"base" as "sm"|"base"|"lg",bold:false});const [newEvent,setNewEvent]=useState({date:todayString(),title:"",type:"Study",color:eventColors[1]});const [utcOffset,setUtcOffset]=useState("-5");const [localTime,setLocalTime]=useState("14:00");const [utcAnswer,setUtcAnswer]=useState("");const [utcFeedback,setUtcFeedback]=useState("");const [quizIndex,setQuizIndex]=useState(0);const [quizScore,setQuizScore]=useState(0);const [quizAnswer,setQuizAnswer]=useState<number|null>(null);const [testAnswers,setTestAnswers]=useState<Record<number,number>>({});const [testSubmitted,setTestSubmitted]=useState(false);const [airportSearch,setAirportSearch]=useState("");const [flashIndex,setFlashIndex]=useState(0);const [aircraftSelected,setAircraftSelected]=useState("Door");const [shareTitle,setShareTitle]=useState("");const [shareUser,setShareUser]=useState("");const [shareMessage,setShareMessage]=useState("");
 const today=todayString();const quote=dailyQuotes[new Date().getDate()%dailyQuotes.length];const upcoming=useMemo(()=>events.filter(e=>e.date>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4),[events,today]);const filteredAirports=useMemo(()=>airports.filter(a=>`${a.city} ${a.code}`.toLowerCase().includes(airportSearch.toLowerCase())).slice(0,30),[airportSearch]);useEffect(()=>{if(typeof window!=="undefined"&&"serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
 function go(next:Tab){setTab(next);setMenuOpen(false);setSelectedLesson(null);window.scrollTo({top:0,behavior:"smooth"})} function addNote(){const id=Date.now();setNotes(prev=>[{id,...noteDraft},...prev]);setSelectedNote(id);setNoteDraft({title:"",text:"",color:noteColors[0],size:"base",bold:false})} function saveNote(){if(selectedNote===null)return;setNotes(prev=>prev.map(n=>n.id===selectedNote?{...n,...noteDraft}:n))} function editNote(note:Note){setSelectedNote(note.id);setNoteDraft({title:note.title,text:note.text,color:note.color,size:note.size,bold:note.bold})} function deleteNote(id:number){setNotes(prev=>prev.filter(n=>n.id!==id));if(selectedNote===id){setSelectedNote(null);setNoteDraft({title:"",text:"",color:noteColors[0],size:"base",bold:false})}}
 function addEvent(){if(!newEvent.title.trim())return;setEvents(prev=>[...prev,{...newEvent,id:Date.now()}].sort((a,b)=>a.date.localeCompare(b.date)));setNewEvent({date:todayString(),title:"",type:"Study",color:eventColors[1]})} function calculateZulu(){const [h,m]=localTime.split(":").map(Number);const offset=Number(utcOffset);if(!Number.isFinite(h)||!Number.isFinite(m)||!Number.isFinite(offset))return;const total=(h*60+m-offset*60+1440)%1440;setUtcAnswer(`${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}Z`);setUtcFeedback(`Local time ${localTime} at UTC${offset>=0?"+":""}${offset} converts to UTC by subtracting the offset. The clock moves ${offset>0?"back":"forward"} ${Math.abs(offset)} hour${Math.abs(offset)===1?"":"s"}.`)} function answerQuiz(i:number){setQuizAnswer(i);if(i===questions[quizIndex].a)setQuizScore(s=>s+1)} function nextQuiz(){setQuizAnswer(null);setQuizIndex(i=>(i+1)%questions.length)} function submitTest(){setTestSubmitted(true)} function countTestCorrect(){return questions.reduce((n,q,i)=>n+(testAnswers[i]===q.a?1:0),0)}
 async function handlePackageUpload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;let pages=0;if(file.type==="application/pdf"){try{const buffer=await file.arrayBuffer();const text=new TextDecoder("latin1").decode(buffer);pages=Math.max(1,(text.match(/\/Type\s*\/Page(?!s)/g)||[]).length)}catch{pages=0}}setPackageInfo({name:file.name,size:file.size,pages,date:new Date().toISOString()})}
 const packageSize=packageInfo?`${(packageInfo.size/1024/1024).toFixed(1)} MB`:"";const progress=Math.round((Object.values(completed).filter(Boolean).length/(courses.length*4))*100);const testPercent=Math.round((countTestCorrect()/questions.length)*100);
 return <main className="cr-shell"><header className="cr-header"><button className="brand" onClick={()=>go("home")} aria-label="CabinReady home"><span className="brand-mark">✈</span><span><strong>CabinReady</strong><small>Flight Attendant Training</small></span></button><div className="header-actions"><div className="sync-pill"><span className="dot"/> Saved on this device</div><button className="plane-menu" onClick={()=>setMenuOpen(v=>!v)} aria-label="Open main menu">✈</button></div></header>
 {menuOpen&&<div className="menu-backdrop" onClick={()=>setMenuOpen(false)}><aside className="main-menu" onClick={e=>e.stopPropagation()}><div className="menu-head"><div><span className="eyebrow">CABINREADY</span><h2>Main Menu</h2></div><button className="icon-btn" onClick={()=>setMenuOpen(false)}>×</button></div><div className="menu-grid">{menuItems.map(item=><button key={item.id} className={`menu-item ${tab===item.id?"active":""}`} onClick={()=>go(item.id)}><span className="menu-icon">{item.icon}</span><span><b>{item.label}</b><small>{item.desc}</small></span></button>)}</div></aside></div>}
 <div className="cr-content"><div className="topbar"><button className="back-btn" onClick={()=>go("home")}>← Home</button><span className="crumb">{menuItems.find(x=>x.id===tab)?.label}</span></div>
 {tab==="home"&&<section><div className="hero"><div><span className="eyebrow">CABINREADY</span><h1>Build your knowledge, confidence & recall before training day.</h1><p>A focused training workspace that keeps the learning in your hands. AI is optional and stays out of the way unless you ask for help.</p><div className="hero-actions"><button className="primary" onClick={()=>go("study")}>Start studying</button><button className="secondary" onClick={()=>go("package")}>Upload training package</button></div></div><div className="hero-plane">✈</div></div><div className="dashboard-grid"><div className="card reminder"><div className="section-title"><span>Today's reminder</span><span>✦</span></div><p>“{quote}”</p></div><div className="card upcoming"><div className="section-title"><span>Upcoming</span><button onClick={()=>go("calendar")}>Calendar →</button></div>{upcoming.length?upcoming.map(e=><button className="event-row" key={e.id} onClick={()=>go("calendar")}><span className="event-dot" style={{background:e.color}}/><span><b>{e.title}</b><small>{formatDate(e.date)} · {e.type}</small></span></button>):<p className="muted">No upcoming items. Add one to your calendar.</p>}</div></div><h2 className="section-heading">Study shortcuts</h2><div className="shortcut-grid">{[["package","▣","Training Package","Upload and manage your training files"],["practice","◉","Practice Lab","UTC, Zulu and skill drills"],["quiz","?","Quick Quiz","Instant feedback without AI"],["aircraft","✈","Aircraft Lab","Explore the A220 study model"],["notes","✎","Notes","Write, edit and organize your notes"],["passport","▥","Training Passport","See progress and weak areas"]].map(([id,icon,title,desc])=><button key={id} className="shortcut" onClick={()=>go(id as Tab)}><span>{icon}</span><b>{title}</b><small>{desc}</small></button>)}</div></section>}
 {tab==="training"&&<section><PageTitle title="Training Hub" sub="Your command center for the work that matters most."/><div className="hub-grid"><div className="card large"><span className="eyebrow">NEXT UP</span><h2>{upcoming[0]?.title||"Add your first training event"}</h2><p>{upcoming[0]?formatDate(upcoming[0].date):"Use the calendar to schedule exams, homework, study sessions and training days."}</p><button className="primary" onClick={()=>go("calendar")}>{upcoming[0]?"Open calendar":"Build your calendar"}</button></div><div className="card"><span className="eyebrow">PROGRESS</span><strong className="big-number">{progress}%</strong><p>Training journey complete</p><div className="progress"><span style={{width:`${progress}%`}}/></div></div><div className="card"><span className="eyebrow">PACKAGE</span><h3>{packageInfo?packageInfo.name:"No package uploaded"}</h3><p>{packageInfo?`${packageSize} · ${packageInfo.pages?`${packageInfo.pages} detected pages`:"page count pending"}`:"Your training package gets its own workspace."}</p><button className="secondary" onClick={()=>go("package")}>{packageInfo?"Open package":"Upload package"}</button></div><div className="card"><span className="eyebrow">STUDY TOGETHER</span><h3>Share notes inside CabinReady</h3><p>Username-based sharing is prepared in the notes workspace. Cloud-to-cloud sharing needs account/database services.</p><button className="secondary" onClick={()=>go("notes")}>Open notes</button></div></div></section>}
 {tab==="package"&&<section><PageTitle title="Training Package" sub="A separate home for the official material that powers your training."/><div className="card upload-card"><div className="upload-icon">▣</div><h2>{packageInfo?"Training package saved":"Upload your training package"}</h2><p>CabinReady can keep the package metadata locally and prepare it for analysis. The app will not invent airline-specific procedures before the official material is available.</p><label className="upload-btn">Choose PDF<input type="file" accept="application/pdf,.pdf" onChange={handlePackageUpload} hidden/></label>{packageInfo&&<div className="package-summary"><b>{packageInfo.name}</b><span>{packageSize}</span><span>{packageInfo.pages?`${packageInfo.pages} pages detected`:"Page count could not be confirmed locally"}</span><span>Saved {new Date(packageInfo.date).toLocaleString()}</span></div>}</div><div className="info-grid"><div className="card"><span className="eyebrow">WHAT HAPPENS NEXT</span><h3>Page-by-page organization</h3><p>When an analyzer is connected, each page can be processed, its content classified, and verified material routed to the matching course: Service & Hospitality, Onboard Operations, Medical & First Aid, Breeze Knowledge, Emergency Procedures, and so on.</p></div><div className="card warning"><span className="eyebrow">CURRENT LIMIT</span><h3>No Gemini dependency</h3><p>Gemini is intentionally not required right now. Full automatic document understanding needs a document-analysis service. The rest of the study system works without AI.</p></div></div></section>}
 {tab==="journey"&&<section><PageTitle title="Training Journey" sub="Open a course to study its lessons. Courses are not completed by simply clicking the topic."/><div className="course-list">{courses.map((course,ci)=><div className="course-card" key={course.title}><div className="course-head"><div><span className="eyebrow">COURSE {ci+1}</span><h2>{course.title}</h2><p>{course.subtitle}</p></div><span className="course-progress">{course.lessons.filter((_,li)=>completed[`${ci}-${li}`]).length}/4</span></div><div className="lesson-grid">{course.lessons.map((lesson,li)=><button className="lesson" key={lesson.title} onClick={()=>setSelectedLesson({course:ci,lesson:li})}><span>{String(li+1).padStart(2,"0")}</span><div><b>{lesson.title}</b><small>{completed[`${ci}-${li}`]?"Reviewed":"Open lesson →"}</small></div>{completed[`${ci}-${li}`]&&<em>✓</em>}</button>)}</div></div>)}</div>{selectedLesson&&<div className="lesson-modal"><div className="modal-card"><button className="modal-close" onClick={()=>setSelectedLesson(null)}>×</button><span className="eyebrow">COURSE {selectedLesson.course+1}</span><h2>{courses[selectedLesson.course].lessons[selectedLesson.lesson].title}</h2><p>{courses[selectedLesson.course].lessons[selectedLesson.lesson].body}</p><button className="primary" onClick={()=>{setCompleted(prev=>({...prev,[`${selectedLesson.course}-${selectedLesson.lesson}`]:true}));setSelectedLesson(null)}}>{completed[`${selectedLesson.course}-${selectedLesson.lesson}`]?"Reviewed":"Mark lesson reviewed"}</button></div></div>}</section>}
 {tab==="study"&&<section><PageTitle title="Study Center" sub="Learn first. Use AI only when you deliberately ask for help."/><div className="topic-grid">{[["Aviation Foundations","Aircraft basics, UTC/Zulu, airport codes and phonetic alphabet","journey"],["Cabin Crew","Role, communication, professionalism and cabin readiness","journey"],["Aviation Terminology","Core language used in aviation operations","phonetic"],["Emergency & Safety","Verified emergency and safety material from your package","journey"],["Service & Hospitality","Guest experience and service standards","journey"],["Medical & First Aid","Medical response and first-aid study area","journey"]].map(([title,desc,target])=><button className="topic-card" key={title} onClick={()=>go(target as Tab)}><span className="topic-number">•</span><b>{title}</b><p>{desc}</p><span className="link">Open subject →</span></button>)}</div></section>}
 {tab==="practice"&&<section><PageTitle title="Practice Lab" sub="Work the problem yourself, then see exactly why the answer works."/><div className="practice-grid"><div className="card"><span className="eyebrow">UTC / ZULU CALCULATOR</span><h2>Convert local time → Zulu</h2><div className="form-grid"><label>UTC offset<select value={utcOffset} onChange={e=>setUtcOffset(e.target.value)}>{[-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12].map(n=><option key={n} value={n}>{n>0?`+${n}`:n}</option>)}</select></label><label>Local time<input type="time" value={localTime} onChange={e=>setLocalTime(e.target.value)}/></label></div><button className="primary" onClick={calculateZulu}>Calculate Zulu</button>{utcAnswer&&<div className="answer-box"><strong>{utcAnswer}</strong><p>{utcFeedback}</p></div>}</div><div className="card"><span className="eyebrow">RULE TO REMEMBER</span><h2>The number-line idea</h2><p>UTC+ means local time is ahead of UTC, so local → UTC subtracts the positive offset. UTC− means local time is behind UTC, so local → UTC adds the absolute value of the negative offset.</p><div className="time-line"><span>UTC−5</span><span>←</span><strong>UTC / Z</strong><span>→</span><span>UTC+3</span></div><p className="muted">Always check whether crossing midnight changes the calendar date.</p></div></div><div className="card drill-card"><span className="eyebrow">WHY DID I GET IT WRONG?</span><h2>Immediate explanations</h2><p>Practice answers in the Quiz and Final Test are graded locally. Every incorrect answer includes an explanation rather than only a red X.</p><button className="secondary" onClick={()=>go("quiz")}>Start a quiz</button></div></section>}
 {tab==="quiz"&&<section><PageTitle title="Quick Quiz" sub="No AI required. Questions come from CabinReady's verified study bank."/><div className="quiz-card"><div className="quiz-meta"><span>Question {quizIndex+1} of {questions.length}</span><span>Score {quizScore}</span></div><h2>{questions[quizIndex].q}</h2><div className="answer-list">{questions[quizIndex].o.map((option,i)=><button key={option} disabled={quizAnswer!==null} className={`answer-option ${quizAnswer!==null&&i===questions[quizIndex].a?"correct":""} ${quizAnswer===i&&i!==questions[quizIndex].a?"wrong":""}`} onClick={()=>answerQuiz(i)}>{option}</button>)}</div>{quizAnswer!==null&&<div className={`feedback ${quizAnswer===questions[quizIndex].a?"good":"bad"}`}><b>{quizAnswer===questions[quizIndex].a?"Correct":"Not quite"}</b><p>{questions[quizIndex].e}</p><button className="secondary" onClick={nextQuiz}>Next question →</button></div>}</div></section>}
 {tab==="test"&&<section><PageTitle title="Final Test" sub="A graded test so your brain gets used to seeing a real score."/>{!testSubmitted?<div className="test-card">{questions.map((q,i)=><div className="test-question" key={q.q}><span className="eyebrow">{i+1} / {questions.length} · {q.topic}</span><h3>{q.q}</h3><div className="mini-options">{q.o.map((o,j)=><label key={o}><input type="radio" name={`q${i}`} checked={testAnswers[i]===j} onChange={()=>setTestAnswers(prev=>({...prev,[i]:j}))}/>{o}</label>)}</div></div>)}<button className="primary wide" onClick={submitTest}>Submit graded test</button></div>:<div className="result-card"><span className="eyebrow">FINAL SCORE</span><strong className="score">{testPercent}%</strong><p>{countTestCorrect()} of {questions.length} correct.</p><div className="test-review">{questions.map((q,i)=><div key={q.q} className={testAnswers[i]===q.a?"review-good":"review-bad"}><b>{i+1}. {q.q}</b><span>{testAnswers[i]===q.a?"Correct":"Incorrect"} · {q.e}</span></div>)}</div><button className="secondary" onClick={()=>{setTestSubmitted(false);setTestAnswers({})}}>Retake test</button></div>}</section>}
 {tab==="flashcards"&&<section><PageTitle title="Flashcards" sub="Flip through active-recall prompts without giving yourself the answer first."/><div className="flashcard-wrap"><button className="flashcard" onClick={()=>setFlashIndex(i=>(i+1)%flashcards.length)}><span className="eyebrow">CARD {flashIndex+1} / {flashcards.length}</span><h2>{flashcards[flashIndex][0]}</h2><p>{flashcards[flashIndex][1]}</p><small>Tap for the next card</small></button><div className="pager"><button onClick={()=>setFlashIndex(i=>(i-1+flashcards.length)%flashcards.length)}>← Previous</button><button onClick={()=>setFlashIndex(i=>(i+1)%flashcards.length)}>Next →</button></div></div></section>}
 {tab==="aircraft"&&<section><PageTitle title="Aircraft Lab" sub="Interactive study model. Exact A220 equipment locations will be populated from your official training package."/><div className="aircraft-layout"><div className="aircraft-model"><div className="aircraft-nose">COCKPIT</div><div className="cabin-body"><div className="cabin-label">FORWARD GALLEY</div><div className="seats">{Array.from({length:10}).map((_,i)=><div key={i} className="seat-row">{["A","B","C","D","E","F"].map(s=><button key={s} className="seat" onClick={()=>setAircraftSelected(`Seat ${i+1}${s}`)}>{i+1}{s}</button>)}</div>)}</div><button className="cabin-hotspot door" onClick={()=>setAircraftSelected("Door")}>DOOR</button><button className="cabin-hotspot mid" onClick={()=>setAircraftSelected("Mid Galley")}>GALLEY</button><button className="cabin-hotspot aft" onClick={()=>setAircraftSelected("Aft Galley")}>AFT GALLEY</button></div><div className="aircraft-tail">AFT</div></div><div className="card equipment-panel"><span className="eyebrow">SELECTED AREA</span><h2>{aircraftSelected}</h2><p>{aircraftSelected==="Door"?"Aircraft doors are a critical study area. Exact door operation, evacuation equipment and slide configuration must come from your official training package.":aircraftSelected.includes("Galley")?"Study galley functions, equipment and locations from the verified cabin configuration.":aircraftSelected.startsWith("Seat")?"Seat location selected. Exact emergency-row designations and equipment locations should be verified against the official package.":"Explore the cabin study model."}</p><div className="equipment-list"><button onClick={()=>setAircraftSelected("Emergency Equipment")}>Emergency equipment</button><button onClick={()=>setAircraftSelected("Exit Rows")}>Exit rows</button><button onClick={()=>setAircraftSelected("Oxygen Masks")}>Oxygen masks</button><button onClick={()=>setAircraftSelected("Slide / Raft")}>Slide / raft</button></div></div></div></section>}
 {tab==="passport"&&<section><PageTitle title="Training Passport" sub="Your progress lives here — not on the main screen."/><div className="passport-wrap"><div className="passport"><div className="passport-cover"><span>✈</span><b>CABINREADY</b><small>TRAINING PASSPORT</small><i>Student Edition</i></div><div className="passport-page"><div><span className="eyebrow">PROGRESS</span><strong>{progress}%</strong><p>Training journey</p></div><div><span className="eyebrow">STAMP</span><div className="stamp">IN TRAINING</div></div></div><div className="passport-page stamps">{courses.slice(0,4).map((c,i)=><div className={`stamp ${completed[`${i}-0`]?"earned":""}`} key={c.title}>{completed[`${i}-0`]?"✓":"○"}<small>{c.title}</small></div>)}</div></div><div className="card weak"><span className="eyebrow">WORK ON THESE</span><h2>Weak areas</h2><p>Use quiz/test results and your own notes to decide what needs more practice. Airline-specific weaknesses will become measurable after your package is uploaded and your study content is built.</p><button className="secondary" onClick={()=>go("practice")}>Practice weak areas</button></div></div></section>}
 {tab==="calendar"&&<section><PageTitle title="Calendar" sub="Color-code the entire selected calendar date so important days stand out."/><div className="calendar-layout"><div className="card"><div className="calendar-head"><h2>September 2026</h2><span>Color-coded</span></div><div className="calendar-week">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{Array.from({length:30}).map((_,i)=>{const date=`2026-09-${String(i+1).padStart(2,"0")}`;const ev=events.find(e=>e.date===date);return <button key={date} className="day-cell" style={ev?{background:ev.color,color:"#fff"}:{}} onClick={()=>setNewEvent(v=>({...v,date}))}><b>{i+1}</b>{ev&&<small>{ev.title}</small>}</button>})}</div></div><div className="card"><span className="eyebrow">ADD CALENDAR ITEM</span><label>Date<input type="date" value={newEvent.date} onChange={e=>setNewEvent(v=>({...v,date:e.target.value}))}/></label><label>Title<input placeholder="Day 1 of training, exam, homework..." value={newEvent.title} onChange={e=>setNewEvent(v=>({...v,title:e.target.value}))}/></label><label>Type<select value={newEvent.type} onChange={e=>setNewEvent(v=>({...v,type:e.target.value}))}>{eventTypes.map(t=><option key={t}>{t}</option>)}</select></label><div><span className="field-label">Date color</span><div className="color-row">{eventColors.map(c=><button key={c} className="color-dot" style={{background:c}} onClick={()=>setNewEvent(v=>({...v,color:c}))}/>)}</div></div><button className="primary wide" onClick={addEvent}>Add item to calendar</button><div className="event-list">{[...events].sort((a,b)=>a.date.localeCompare(b.date)).map(e=><div className="event-manage" key={e.id}><span className="event-dot" style={{background:e.color}}/><span><b>{e.title}</b><small>{formatDate(e.date)} · {e.type}</small></span><button onClick={()=>setEvents(prev=>prev.filter(x=>x.id!==e.id))}>Delete</button></div>)}</div></div></div></section>}
 {tab==="notes"&&<section><PageTitle title="Notes" sub="Write it down, change it later, resize it, recolor it, or delete it."/><div className="notes-layout"><div className="card note-editor"><span className="eyebrow">NOTE EDITOR</span><input className="title-input" placeholder="Note title" value={noteDraft.title} onChange={e=>setNoteDraft(v=>({...v,title:e.target.value}))}/><textarea placeholder="Write your study notes..." value={noteDraft.text} onChange={e=>setNoteDraft(v=>({...v,text:e.target.value}))} style={{fontSize:noteDraft.size==="sm"?14:noteDraft.size==="lg"?20:16,fontWeight:noteDraft.bold?700:400}}/><div className="toolbar"><div className="color-row">{noteColors.map(c=><button key={c} className="color-dot" style={{background:c}} onClick={()=>setNoteDraft(v=>({...v,color:c}))}/>)}</div><select value={noteDraft.size} onChange={e=>setNoteDraft(v=>({...v,size:e.target.value as Note["size"]}))}><option value="sm">Small</option><option value="base">Normal</option><option value="lg">Large</option></select><button className={noteDraft.bold?"tool active":"tool"} onClick={()=>setNoteDraft(v=>({...v,bold:!v.bold}))}>B</button></div><div className="editor-actions"><button className="secondary" onClick={()=>{setSelectedNote(null);setNoteDraft({title:"",text:"",color:noteColors[0],size:"base",bold:false})}}>New</button>{selectedNote!==null?<button className="primary" onClick={saveNote}>Save changes</button>:<button className="primary" onClick={addNote}>Save note</button>}</div></div><div><div className="note-share card"><span className="eyebrow">STUDY TOGETHER</span><h3>Share notes by CabinReady username</h3><input placeholder="Note title to share" value={shareTitle} onChange={e=>setShareTitle(e.target.value)}/><input placeholder="Recipient username" value={shareUser} onChange={e=>setShareUser(e.target.value)}/><button className="secondary blue-btn" onClick={()=>setShareMessage(shareTitle&&shareUser?`Ready to share “${shareTitle}” with @${shareUser}. Cloud delivery activates with accounts/database.`:"Enter a note title and username first.")}>Share</button>{shareMessage&&<p className="muted">{shareMessage}</p>}</div><div className="notes-list">{notes.map(n=><div className="saved-note" key={n.id} style={{background:n.color}}><div><b>{n.title||"Untitled note"}</b><p className={n.bold?"bold":""}>{n.text}</p></div><div className="note-actions"><button onClick={()=>editNote(n)}>Edit</button><button onClick={()=>deleteNote(n.id)}>Delete</button></div></div>)}{!notes.length&&<div className="empty card">No saved notes yet.</div>}</div></div></div></section>}
 {tab==="airports"&&<section><PageTitle title="Airport Codes" sub="Build recognition of three-letter IATA identifiers."/><div className="card"><input className="search-input" placeholder="Search city or code" value={airportSearch} onChange={e=>setAirportSearch(e.target.value)}/><div className="airport-grid">{filteredAirports.map(a=><div className="airport-row" key={a.code}><b>{a.code}</b><span>{a.city}</span></div>)}</div></div></section>}
 {tab==="phonetic"&&<section><PageTitle title="ICAO Phonetic Alphabet" sub="Alpha through Zulu — practice the alphabet until recall is automatic."/><div className="phonetic-grid">{phonetic.map(([letter,word])=><button className="phonetic-card" key={letter}><strong>{letter}</strong><span>{word}</span></button>)}</div></section>}
 {tab==="ai"&&<section><PageTitle title="AI Study Help" sub="Optional. AI never replaces your own studying."/><div className="card ai-card">{settings.aiEnabled?<><span className="eyebrow">AI ENABLED</span><h2>Ask for an explanation</h2><p>AI assistance is designed for questions like “Break this note down for me” or “Explain this aircraft concept.” It should use your uploaded training material as its source when an analyzer is connected.</p><textarea placeholder="What do you want help understanding?"/><button className="primary" onClick={()=>alert("AI provider is not connected yet. Your study system remains fully usable without it.")}>Ask AI</button></>:<><span className="eyebrow">AI IS OFF</span><h2>Brains first.</h2><p>You asked for AI to stay optional. Turn it on in Settings only when you want an AI explanation or document analysis.</p><button className="secondary" onClick={()=>setSettings(s=>({...s,aiEnabled:true}))}>Enable AI</button></>}</div></section>}
 {tab==="profile"&&<section><PageTitle title="Profile" sub="Your display identity can be separate from your sign-in identity."/><div className="profile-grid"><div className="card"><span className="eyebrow">PROFILE</span><label>Display name<input value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))} placeholder="Your name"/></label><label>Username<input value={profile.username} onChange={e=>setProfile(p=>({...p,username:e.target.value.replace(/\s/g,"").toLowerCase()}))} placeholder="cabinready username"/></label><button className="primary" onClick={()=>localStorage.setItem("cr-profile",JSON.stringify(profile))}>Save profile</button></div><div className="card"><span className="eyebrow">ACCOUNT</span><h3>Google & Apple sign-in</h3><p>These buttons should not pretend to authenticate until a real identity provider and database are connected. The current profile is local to this browser.</p><div className="auth-placeholder"><button disabled>Continue with Apple · setup required</button><button disabled>Continue with Google · setup required</button></div></div></div></section>}
 {tab==="settings"&&<section><PageTitle title="Settings" sub="Choose how much assistance you want CabinReady to provide."/><div className="settings-list"><div className="setting-row"><div><b>AI assistance</b><p>Optional explanations and future package analysis.</p></div><button className={`toggle ${settings.aiEnabled?"on":""}`} onClick={()=>setSettings(s=>({...s,aiEnabled:!s.aiEnabled}))}><span/></button></div><div className="setting-row"><div><b>Offline study mode</b><p>Keep studying with locally saved notes, calendar, flashcards and quizzes. AI is unavailable offline.</p></div><button className={`toggle ${settings.offline?"on":""}`} onClick={()=>setSettings(s=>({...s,offline:!s.offline}))}><span/></button></div><div className="setting-row"><div><b>Current account model</b><p>Local device storage is active. Cross-device sync, Google/Apple sign-in and Study Together cloud sharing require a backend database/auth layer.</p></div><span className="status-badge">Local only</span></div></div></section>}
 </div><footer className="cr-footer"><span>CabinReady · Study first, assistance second.</span><span>{settings.offline?"Offline mode on":"Online mode"}</span></footer></main>;
}
function PageTitle({title,sub}:{title:string;sub:string}){return <div className="page-title"><div><span className="eyebrow">CABINREADY</span><h1>{title}</h1><p>{sub}</p></div></div>}
